#!/usr/bin/env python3
"""PNG sprites to LVGL 9 image arrays, for the PocketTimber build.

    png2lvgl.py <rendered-dir> <out-dir>

Reads rendered/anchors.json and every PNG it names, and writes one C file
per image (ARGB8888 for sprites, A8 for the shadow, RGB888 for the felt)
plus timber_art_table.c, which lists every sprite with its anchor: the
pixel the engine's far-bottom corner of the block lands on. The view
places a sprite at (projected corner - anchor).

Nothing here is committed: ui/shell/CMakeLists.txt runs this at configure
time into the build directory. Standard library only, so the build host
needs nothing beyond python3.
"""
import json
import os
import sys

sys.dont_write_bytecode = True          # a build must leave no __pycache__ in the tree
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngio import read_png  # noqa: E402

FORMATS = {
    "felt": ("LV_COLOR_FORMAT_RGB888", 3),
    "shadow": ("LV_COLOR_FORMAT_A8", 1),
}


def c_name(key):
    return "timber_art_img_" + key.replace("-", "_")


def write_image(out_dir, key, path):
    w, h, rows = read_png(path)
    cf, bpp = FORMATS.get(key, ("LV_COLOR_FORMAT_ARGB8888", 4))
    name = c_name(key)
    data = bytearray()
    for row in rows:
        for r, g, b, a in row:
            if bpp == 4:
                data.extend((b, g, r, a))      # lv_color32_t: blue, green, red, alpha
            elif bpp == 3:
                data.extend((b, g, r))
            else:
                data.append(a)
    lines = ["/* Generated by docs/design/timber-art/tools/png2lvgl.py from %s. Do not edit. */" % os.path.basename(path),
             '#include "lvgl.h"', "",
             "static const uint8_t %s_map[] LV_ATTRIBUTE_MEM_ALIGN = {" % name]
    for i in range(0, len(data), 24):
        lines.append("    " + ",".join("0x%02x" % v for v in data[i:i + 24]) + ",")
    lines += ["};", "",
              "const lv_image_dsc_t %s = {" % name,
              "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
              "    .header.cf = %s," % cf,
              "    .header.flags = 0,",
              "    .header.w = %d," % w,
              "    .header.h = %d," % h,
              "    .header.stride = %d," % (w * bpp),
              "    .data_size = sizeof(%s_map)," % name,
              "    .data = %s_map," % name,
              "};", ""]
    with open(os.path.join(out_dir, name + ".c"), "w") as f:
        f.write("\n".join(lines))
    return name, w, h


def main(rendered, out_dir):
    with open(os.path.join(rendered, "anchors.json")) as f:
        manifest = json.load(f)
    os.makedirs(out_dir, exist_ok=True)
    for stale in os.listdir(out_dir):          # a rename or a dropped sprite must not linger
        if stale.startswith("timber_art_") and stale.endswith(".c"):
            os.remove(os.path.join(out_dir, stale))
    sprites = manifest["sprites"]
    table = ["/* Generated by docs/design/timber-art/tools/png2lvgl.py. Do not edit. */",
             '#include "timber_art.h"', ""]
    entries = []
    for key, info in sprites.items():
        name, w, h = write_image(out_dir, key, os.path.join(rendered, info["file"]))
        table.append("LV_IMAGE_DECLARE(%s);" % name)
        entries.append((key, name, info))
    table.append("")
    table.append("const struct timber_art_sprite timber_art_sprites[] = {")
    for key, name, info in entries:
        table.append('    { "%s", &%s, %d, %d },' % (key, name, int(round(info.get("ax", 0))), int(round(info.get("ay", 0)))))
    table.append("};")
    table.append("const int timber_art_sprite_count = %d;" % len(entries))
    table.append("const int timber_art_scale_px = %d;" % manifest["scale_px"])
    table.append("const int timber_art_layer_px = %d;" % manifest["layer_px"])
    table.append("")
    with open(os.path.join(out_dir, "timber_art_table.c"), "w") as f:
        f.write("\n".join(table))
    print("png2lvgl: %d images into %s" % (len(entries), out_dir))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
