/*
 * System Status: the screen. Everything it *decides* is in system_view.c;
 * this builds the panels and turns taps into those decisions.
 *
 * Four short pages under a row of tabs (DS §52.5), in place of the one long
 * page with two scrolling columns it used to be:
 *
 *   OVERVIEW  CPU, temperature, memory, load, uptime, clock; storage; and
 *             Restart and Power off, last
 *   NETWORK   the interfaces, their addresses and their traffic; Wi-Fi; the
 *             LoRa radio and its packets; the mesh (system_net.c)
 *   SERVICES  the supervised services, and the way into Diagnostics
 *   ABOUT     the build, the card, the model, the kernel, the platform
 *
 * It reads nothing from the machine directly - no /proc, no /sys, no
 * /run/pocketos. system.info once at create, system.status every two seconds
 * over pocketipc while a page that shows it is up, and the radio state the
 * shell's status bar has already polled; the Network page adds one call a
 * second between radiod, netd and meshcored. Every call carries
 * SHELL_IPC_UI_TIMEOUT_MS, so a service that has stopped answering costs one
 * frame and never the session (unit A, M5).
 *
 * LAYOUT. Each page in two shapes, chosen from the body the app is given and
 * chosen again whenever that body changes size (see "the layout" below): the
 * panels one above the other when the body is tall, two to a row when it is
 * wide. The orientation is the system's (DS section 21.2); nothing here asks
 * what it is, only how much room there is.
 *
 * DIAGNOSTICS. A page of its own behind a button on SERVICES: a summary from
 * sysd, radiod and meshcored, the crash reports and the newest log lines with
 * All / Warnings / Errors, for diagnosing the device without SSH. What it
 * says is diag_view.c's; it refreshes one bounded call per tick
 * (diag_view.h), and holds at most DIAG_LOG_MAX log lines.
 *
 * Copyright (c) 2026 PocketOS authors.
 * SPDX-License-Identifier: Apache-2.0
 */
#define _GNU_SOURCE
#include "app.h"
#include "diag_view.h"
#include "pocketui.h"
#include "shell_ipc.h"
#include "system_internal.h"
#include "system_view.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* system.status every other tick. The shell ticks apps once a second and
 * already polls radiod at that rate; a status screen does not need to be
 * faster, and this halves what the two of them ask for together. */
#define SYSTEM_POLL_TICKS 2

/* The Doors compact mark, an A8 mask generated by tools/design/gen_brand_mark.py. */
LV_IMAGE_DECLARE(pos_brand_mark);

static void rebuild(struct system_app *a);
static void arrange(struct system_app *a);

static const char *const tab_labels[SYSTEM_TAB_COUNT] = { "OVERVIEW", "NETWORK", "SERVICES", "ABOUT" };

/* ---- small builders ---------------------------------------------------- */

/* A panel in one of the page's two columns, or straight in the body when the
 * page has none (Diagnostics, a confirmation). */
lv_obj_t *system_panel(struct system_app *a, enum system_col col)
{
    lv_obj_t *p = pocketui_card(a->col[0] ? a->col[col == SYSTEM_COL_RIGHT ? 1 : 0] : a->body);

    lv_obj_set_style_pad_row(p, 0, 0);
    return p;
}

/* A box that stacks panels SYSTEM_PANEL_GAP apart, as tall as its content: a
 * column of panels, or the two columns. Which way it lies and how wide it is
 * are the layout's (arrange). It never scrolls - the page does - and it stays
 * clickable, as every box here is: a finger that lands in the gap between two
 * panels still has to drag the page, and LVGL only finds a clickable object
 * there. */
static lv_obj_t *stack(lv_obj_t *parent)
{
    lv_obj_t *s = lv_obj_create(parent);

    lv_obj_remove_style_all(s);
    lv_obj_set_size(s, LV_PCT(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(s, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(s, SYSTEM_PANEL_GAP, 0);
    lv_obj_set_style_pad_column(s, SYSTEM_PANEL_GAP, 0);
    lv_obj_clear_flag(s, LV_OBJ_FLAG_SCROLLABLE);
    return s;
}

lv_obj_t *system_chip(lv_obj_t *parent, const char *text, enum pos_style_role role)
{
    lv_obj_t *c = lv_label_create(parent);

    pos_style_add(c, POS_STYLE_CHIP, 0);
    pos_style_add(c, role, 0);
    lv_label_set_text(c, text);
    return c;
}

lv_obj_t *system_wrap_label(lv_obj_t *parent, const char *text, enum pos_style_role role)
{
    lv_obj_t *lb = pocketui_label(parent, text, role);

    lv_label_set_long_mode(lb, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(lb, LV_PCT(100));
    return lb;
}

/* A row with a label on the left and two objects on the right is the shape
 * most of this screen is made of; this is the container for one. */
lv_obj_t *system_row(lv_obj_t *parent, int height)
{
    lv_obj_t *r = lv_obj_create(parent);

    lv_obj_remove_style_all(r);
    pos_style_add(r, POS_STYLE_DIVIDER, 0);
    lv_obj_set_width(r, LV_PCT(100));
    lv_obj_set_height(r, height);
    lv_obj_set_flex_flow(r, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(r, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(r, LV_OBJ_FLAG_SCROLLABLE);
    return r;
}

/* A row whose last item may need a line of its own: the items wrap rather
 * than share out a fixed width, and the row grows from its 64 px. One line
 * stays one line, centred as it was. A larger text size (DS §46.5) made an
 * address or a service's reason too wide for the share it had, and it was
 * cut where it matters most - at the end. */
void system_row_may_wrap(lv_obj_t *r)
{
    lv_obj_set_flex_flow(r, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_height(r, LV_SIZE_CONTENT);
    lv_obj_set_style_min_height(r, POCKETUI_ROW_H, 0);
}

/* One vitals cell: caption above, value below, half the panel wide. Two per
 * row, three rows, so the six numbers fit in the height of four list rows. */
static lv_obj_t *vitals_cell(lv_obj_t *parent, const char *label)
{
    lv_obj_t *cell = lv_obj_create(parent);
    lv_obj_t *value;

    lv_obj_remove_style_all(cell);
    lv_obj_set_width(cell, LV_PCT(50));
    lv_obj_set_height(cell, POCKETUI_ROW_H);
    lv_obj_set_flex_flow(cell, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cell, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cell, LV_OBJ_FLAG_SCROLLABLE);
    pocketui_label(cell, label, POS_STYLE_CAPTION);
    value = pocketui_label(cell, SYSTEM_VIEW_UNKNOWN, POS_STYLE_VALUE);
    lv_obj_set_width(value, LV_PCT(96));
    /* One line under its caption, at any text size (DS §46.5). */
    pocketui_label_fit(value, 1);
    return value;
}

/* The identity row: a key/value row (DS §9) whose key is the Doors mark and
 * the name. Same height, divider, fonts and value treatment as
 * pocketui_kv_row(); the mark only moves the name 28 px right. The mark
 * takes its colour from POS_STYLE_BRAND_MARK, so it follows the theme and
 * display mode, and it is never animated (DS §19). */
static lv_obj_t *identity_row(lv_obj_t *parent, const char *name, const char *value)
{
    lv_obj_t *r = system_row(parent, POCKETUI_ROW_H);
    lv_obj_t *key = lv_obj_create(r);
    lv_obj_t *mark;
    lv_obj_t *v;

    lv_obj_remove_style_all(key);
    lv_obj_set_size(key, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(key, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(key, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(key, SYSTEM_MARK_GAP, 0);
    lv_obj_clear_flag(key, LV_OBJ_FLAG_SCROLLABLE);
    mark = lv_image_create(key);
    lv_obj_remove_style_all(mark);
    pos_style_add(mark, POS_STYLE_BRAND_MARK, 0);
    lv_image_set_src(mark, &pos_brand_mark);
    pocketui_label(key, name, POS_STYLE_TEXT_SECONDARY);

    v = pocketui_label(r, value, POS_STYLE_VALUE);
    lv_label_set_long_mode(v, LV_LABEL_LONG_DOT);
    lv_obj_set_style_max_width(v, LV_PCT(60), 0);
    return v;
}

static lv_obj_t *vitals_row(lv_obj_t *parent)
{
    lv_obj_t *r = lv_obj_create(parent);

    lv_obj_remove_style_all(r);
    lv_obj_set_width(r, LV_PCT(100));
    lv_obj_set_height(r, POCKETUI_ROW_H);
    lv_obj_set_flex_flow(r, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(r, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(r, LV_OBJ_FLAG_SCROLLABLE);
    return r;
}

/* The freshness line. The app header belongs to the shell, so this sits under
 * the tabs instead, right-aligned: it has to be seen before any number below
 * it, because every one of them is only worth what this line says it is. */
static void build_freshness(struct system_app *a)
{
    lv_obj_t *r = lv_obj_create(a->body);

    lv_obj_remove_style_all(r);
    lv_obj_set_width(r, LV_PCT(100));
    lv_obj_set_height(r, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(r, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(r, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(r, LV_OBJ_FLAG_SCROLLABLE);
    a->freshness_row = r;
    a->freshness = pocketui_label(r, a->view.freshness, POS_STYLE_CAPTION);
}

/* Demote a button from the accent treatment to the restrained one. The
 * pressed style goes with it, or the accent would come back under a finger. */
static void restrain(lv_obj_t *btn)
{
    lv_obj_remove_style(btn, pos_style(POS_STYLE_BUTTON_PRIMARY), 0);
    lv_obj_remove_style(btn, pos_style(POS_STYLE_BUTTON_PRIMARY_PRESSED), LV_STATE_PRESSED);
    pos_style_add(btn, POS_STYLE_BUTTON_SECONDARY, 0);
}

void system_section_caption(lv_obj_t *parent, const char *text)
{
    lv_obj_t *lb = pocketui_label(parent, text, POS_STYLE_CAPTION);

    lv_obj_set_style_pad_bottom(lb, 8, 0);
}

/* ---- painting the live values ------------------------------------------ */

static enum pos_style_role service_chip_role(enum system_view_service_state s)
{
    if (s == SYSTEM_VIEW_SVC_RUNNING) {
        return POS_STYLE_CHIP_ACTIVE;
    }
    if (s == SYSTEM_VIEW_SVC_CRASHLOOP) {
        return POS_STYLE_CHIP_TX;
    }
    return POS_STYLE_CHIP_OFF;
}

enum pos_style_role system_radio_chip_role(enum system_view_radio_chip s)
{
    if (s == SYSTEM_VIEW_RADIO_RX) {
        return POS_STYLE_CHIP_RX;
    }
    if (s == SYSTEM_VIEW_RADIO_TX) {
        return POS_STYLE_CHIP_TX;
    }
    /* Idle is a radio that answered; unknown is one that did not. The status
     * bar has always drawn that distinction and this row now matches it. */
    return s == SYSTEM_VIEW_RADIO_IDLE ? POS_STYLE_CHIP_OFF : POS_STYLE_CHIP_NA;
}

static const char *service_chip_text(enum system_view_service_state s)
{
    if (s == SYSTEM_VIEW_SVC_RUNNING) {
        return "RUNNING";
    }
    if (s == SYSTEM_VIEW_SVC_CRASHLOOP) {
        return "CRASH LOOP";
    }
    return "STOPPED";
}

static void repaint(struct system_app *a)
{
    const struct system_view *v = &a->view;
    int i;

    if (a->freshness) {
        lv_label_set_text(a->freshness, v->freshness);
        lv_obj_remove_style(a->freshness, pos_style(POS_STYLE_STATUS_WARN_TEXT), 0);
        lv_obj_remove_style(a->freshness, pos_style(POS_STYLE_TEXT_MUTED), 0);
        pos_style_add(a->freshness, v->stale ? POS_STYLE_STATUS_WARN_TEXT : POS_STYLE_TEXT_MUTED,
                      0);
    }
    for (i = 0; i < SYSTEM_TAB_COUNT; i++) {
        if (a->tab_btn[i]) {
            lv_obj_remove_style(a->tab_btn[i], pos_style(POS_STYLE_BUTTON_PRIMARY), 0);
            lv_obj_remove_style(a->tab_btn[i], pos_style(POS_STYLE_BUTTON_SECONDARY), 0);
            pos_style_add(a->tab_btn[i], i == (int)a->tab ? POS_STYLE_BUTTON_PRIMARY : POS_STYLE_BUTTON_SECONDARY, 0);
        }
    }
    for (i = 0; i < 6; i++) {
        if (!a->vital[i]) {
            continue;
        }
        lv_label_set_text(a->vital[i], v->vitals[i].value);
        lv_obj_remove_style(a->vital[i], pos_style(POS_STYLE_STATUS_WARN_TEXT), 0);
        if (v->vitals[i].warn) {
            pos_style_add(a->vital[i], POS_STYLE_STATUS_WARN_TEXT, 0);
        }
    }
    for (i = 0; i < v->mount_count && i < SYSTEM_VIEW_MAX_MOUNTS; i++) {
        if (a->mount_detail[i]) {
            lv_label_set_text(a->mount_detail[i], v->mounts[i].detail);
        }
        if (a->mount_bar[i]) {
            /* No meter without a denominator: an unknown share is an empty
             * track, never a full bar or a zero that looks like one. */
            lv_obj_set_width(a->mount_bar[i],
                             LV_PCT(v->mounts[i].have_percent ? v->mounts[i].used_percent : 0));
        }
    }
    for (i = 0; i < v->service_count && i < SYSTEM_VIEW_MAX_SERVICES; i++) {
        if (a->svc_chip[i]) {
            lv_label_set_text(a->svc_chip[i], service_chip_text(v->services[i].state));
            lv_obj_remove_style(a->svc_chip[i], pos_style(POS_STYLE_CHIP_ACTIVE), 0);
            lv_obj_remove_style(a->svc_chip[i], pos_style(POS_STYLE_CHIP_TX), 0);
            lv_obj_remove_style(a->svc_chip[i], pos_style(POS_STYLE_CHIP_OFF), 0);
            pos_style_add(a->svc_chip[i], service_chip_role(v->services[i].state), 0);
        }
        if (a->svc_detail[i]) {
            lv_label_set_text(a->svc_detail[i], v->services[i].detail);
        }
    }
    if (a->expand_line) {
        lv_label_set_text(a->expand_line, v->expand_line);
        lv_obj_remove_style(a->expand_line, pos_style(POS_STYLE_STATUS_ERROR_TEXT), 0);
        if (v->expand_warn) {
            pos_style_add(a->expand_line, POS_STYLE_STATUS_ERROR_TEXT, 0);
        }
    }
    system_net_repaint(a);
    if (a->toast) {
        lv_label_set_text(a->toast, v->error);
        if (v->error[0]) {
            lv_obj_clear_flag(a->toast, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(a->toast, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

/* ---- the two destructive actions --------------------------------------- */

static void on_restart(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    system_view_request(&a->view, SYSTEM_VIEW_ACTION_REBOOT);
    rebuild(a);
}

static void on_poweroff(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    system_view_request(&a->view, SYSTEM_VIEW_ACTION_POWEROFF);
    rebuild(a);
}

static void on_expand(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    system_view_request(&a->view, SYSTEM_VIEW_ACTION_EXPAND);
    rebuild(a);
}

static void on_cancel(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    system_view_cancel(&a->view);
    rebuild(a);
}

/* The only place this screen can reach a method that stops the machine, and
 * system_view_confirm() hands one over only from a confirmation. */
static void on_confirm(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);
    const char *method = system_view_confirm(&a->view);
    char err[96];
    cJSON *result;

    if (!method) {
        return;
    }
    err[0] = '\0';
    result = shell_ipc_call_timeout("sysd", method, NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                    sizeof(err));
    if (result) {
        cJSON_Delete(result);
        system_view_action_ok(&a->view);
    } else {
        system_view_action_failed(&a->view, err);
    }
    rebuild(a);
}

/* ---- the tabs ---------------------------------------------------------- */

static void poll_status(struct system_app *a);

static void on_tab(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);
    intptr_t t = (intptr_t)lv_obj_get_user_data(lv_event_get_current_target(e));

    if (t < 0 || t >= SYSTEM_TAB_COUNT || t == (intptr_t)a->tab) {
        return;
    }
    a->tab = (enum system_tab)t;
    a->tick = 0;
    if (a->tab == SYSTEM_TAB_NETWORK) {
        /* The page's own three answers once now, so it opens with them;
         * after this, one a tick in turn. */
        int k;

        a->net_step = SYSTEM_NET_RADIO;
        for (k = 0; k < SYSTEM_NET_STEPS; k++) {
            system_net_poll_step(a);
        }
    }
    rebuild(a);
}

/* Four buttons across the top, the page on show accented, and the freshness
 * line: under them when the body is tall, at the end of their row when it is
 * wide (arrange_live), where it costs no line of its own. The buttons wrap
 * onto a second line rather than shrink below a finger's width when the text
 * size makes their words wider than a quarter of the body. */
static void build_tabs(struct system_app *a)
{
    lv_obj_t *r = lv_obj_create(a->body);
    int i;

    lv_obj_remove_style_all(r);
    lv_obj_set_size(r, LV_PCT(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(r, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(r, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(r, 8, 0);
    lv_obj_set_style_pad_row(r, 8, 0);
    lv_obj_clear_flag(r, LV_OBJ_FLAG_SCROLLABLE);
    a->tabs = r;
    for (i = 0; i < SYSTEM_TAB_COUNT; i++) {
        lv_obj_t *b = pocketui_button(r, tab_labels[i], on_tab, a);

        restrain(b);
        pos_style_add(b, POS_STYLE_SLAB_PRESSED, LV_STATE_PRESSED);
        lv_obj_set_height(b, SYSTEM_ACTION_BTN_H);
        lv_obj_set_width(b, LV_SIZE_CONTENT);
        lv_obj_set_style_min_width(b, POCKETUI_TOUCH_MIN, 0);
        lv_obj_set_style_pad_hor(b, 12, 0);
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_user_data(b, (void *)(intptr_t)i);
        a->tab_btn[i] = b;
    }
    /* ABOUT shows nothing live, so it has no freshness to report. */
    if (a->tab != SYSTEM_TAB_ABOUT) {
        a->freshness = pocketui_label(r, a->view.freshness, POS_STYLE_CAPTION);
        lv_obj_set_style_text_align(a->freshness, LV_TEXT_ALIGN_RIGHT, 0);
    }
}

/* ---- Diagnostics ------------------------------------------------------ */

static void on_diagnostics(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    a->diag = true;
    diag_view_refresh(&a->dv);
    rebuild(a);
}

static void on_diag_back(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    a->diag = false;
    rebuild(a);
}

static void diag_repaint(struct system_app *a);

static void on_diag_refresh(lv_event_t *e)
{
    struct system_app *a = lv_event_get_user_data(e);

    diag_view_refresh(&a->dv);
    diag_repaint(a);
}

static void diag_filter(struct system_app *a, enum diag_filter f)
{
    diag_view_set_filter(&a->dv, f);
    diag_repaint(a);
}

static void on_diag_all(lv_event_t *e)
{
    diag_filter(lv_event_get_user_data(e), DIAG_FILTER_ALL);
}

static void on_diag_warn(lv_event_t *e)
{
    diag_filter(lv_event_get_user_data(e), DIAG_FILTER_WARN);
}

static void on_diag_error(lv_event_t *e)
{
    diag_filter(lv_event_get_user_data(e), DIAG_FILTER_ERROR);
}

static lv_obj_t *button_row(lv_obj_t *parent)
{
    lv_obj_t *buttons = lv_obj_create(parent);

    lv_obj_remove_style_all(buttons);
    lv_obj_set_width(buttons, LV_PCT(100));
    lv_obj_set_height(buttons, SYSTEM_ACTION_BTN_H);
    lv_obj_set_flex_flow(buttons, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(buttons, 8, 0);
    lv_obj_clear_flag(buttons, LV_OBJ_FLAG_SCROLLABLE);
    return buttons;
}

static lv_obj_t *row_button(lv_obj_t *buttons, const char *text, lv_event_cb_t cb, void *user)
{
    lv_obj_t *b = pocketui_button(buttons, text, cb, user);

    lv_obj_set_height(b, SYSTEM_ACTION_BTN_H);
    lv_obj_set_flex_grow(b, 1);
    return b;
}

static lv_obj_t *column_box(lv_obj_t *parent)
{
    lv_obj_t *box = lv_obj_create(parent);

    lv_obj_remove_style_all(box);
    lv_obj_set_width(box, LV_PCT(100));
    lv_obj_set_height(box, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(box, LV_FLEX_FLOW_COLUMN);
    lv_obj_clear_flag(box, LV_OBJ_FLAG_SCROLLABLE);
    return box;
}

/* The page's fixed part; the crash and log lists are filled by diag_repaint,
 * which replaces them only when a new answer has arrived. */
static void build_diag(struct system_app *a)
{
    lv_obj_t *p;
    lv_obj_t *buttons;
    int i;
    static const lv_event_cb_t filter_cb[DIAG_FILTER_COUNT] = { on_diag_all, on_diag_warn,
                                                                on_diag_error };

    buttons = button_row(a->body);
    restrain(row_button(buttons, "Back", on_diag_back, a));
    row_button(buttons, "Refresh", on_diag_refresh, a);
    a->diag_state = pocketui_label(a->body, "", POS_STYLE_CAPTION);

    p = system_panel(a, SYSTEM_COL_LEFT);
    system_section_caption(p, "DIAGNOSTICS");
    for (i = 0; i < DIAG_ROW_COUNT; i++) {
        lv_obj_t *v = pocketui_kv_row(p, a->dv.rows[i].label, a->dv.rows[i].value);
        lv_obj_t *row = lv_obj_get_parent(v);

        /* These values are read to find out what is wrong, so a long one
         * (a mesh reason, an uncertain radio) wraps in its column rather
         * than losing its end to the dots the System screen's rows use.
         * In the portrait body of the reference panel "Waiting: the radio
         * is switched off" did not fit (tests/system_app_test.c). The row
         * grows with it, never below its height. */
        lv_label_set_long_mode(v, LV_LABEL_LONG_WRAP);
        lv_obj_set_width(v, LV_PCT(60));
        lv_obj_set_style_text_align(v, LV_TEXT_ALIGN_RIGHT, 0);
        lv_obj_set_height(row, LV_SIZE_CONTENT);
        lv_obj_set_style_min_height(row, POCKETUI_ROW_H, 0);
        lv_obj_set_style_pad_ver(row, 8, 0);
        a->diag_value[i] = v;
    }

    p = system_panel(a, SYSTEM_COL_LEFT);
    system_section_caption(p, "CRASH REPORTS");
    a->diag_crash_box = column_box(p);

    p = system_panel(a, SYSTEM_COL_LEFT);
    system_section_caption(p, "LOG");
    buttons = button_row(p);
    for (i = 0; i < DIAG_FILTER_COUNT; i++) {
        a->diag_filter[i] = row_button(buttons, diag_view_filter_label((enum diag_filter)i),
                                       filter_cb[i], a);
        restrain(a->diag_filter[i]);
    }
    a->diag_log_status = pocketui_label(p, "", POS_STYLE_CAPTION);
    lv_obj_set_style_pad_top(a->diag_log_status, 12, 0);
    a->diag_log_box = column_box(p);
    /* Force the first fill. */
    a->diag_built_log = a->dv.log_generation - 1;
    a->diag_built_crash = a->dv.crash_generation - 1;
}

static void set_warn(lv_obj_t *label, int warn)
{
    lv_obj_remove_style(label, pos_style(POS_STYLE_STATUS_WARN_TEXT), 0);
    if (warn) {
        pos_style_add(label, POS_STYLE_STATUS_WARN_TEXT, 0);
    }
}

static void diag_repaint(struct system_app *a)
{
    const struct diag_view *d = &a->dv;
    lv_obj_t *lb;
    int i;

    if (!a->diag_state) {
        return;
    }
    lv_label_set_text(a->diag_state, diag_view_busy(d) ? "Reading..." : "Up to date");
    for (i = 0; i < DIAG_ROW_COUNT; i++) {
        if (a->diag_value[i]) {
            lv_label_set_text(a->diag_value[i], d->rows[i].value);
            set_warn(a->diag_value[i], d->rows[i].warn);
        }
    }
    for (i = 0; i < DIAG_FILTER_COUNT; i++) {
        lv_obj_remove_style(a->diag_filter[i], pos_style(POS_STYLE_SELECTED), 0);
        if ((int)d->filter == i) {
            pos_style_add(a->diag_filter[i], POS_STYLE_SELECTED, 0);
        }
    }
    lv_label_set_text(a->diag_log_status, d->log_status);
    if (a->diag_built_crash != d->crash_generation) {
        a->diag_built_crash = d->crash_generation;
        lv_obj_clean(a->diag_crash_box);
        if (d->crash_count == 0) {
            pocketui_label(a->diag_crash_box, "None on this card", POS_STYLE_TEXT_MUTED);
        }
        for (i = 0; i < d->crash_count; i++) {
            lb = pocketui_label(a->diag_crash_box, d->crashes[i].line, POS_STYLE_TEXT_PRIMARY);
            lv_label_set_long_mode(lb, LV_LABEL_LONG_WRAP);
            lv_obj_set_width(lb, LV_PCT(100));
            if (d->crashes[i].frame[0]) {
                lb = pocketui_label(a->diag_crash_box, d->crashes[i].frame, POS_STYLE_CAPTION);
                lv_label_set_long_mode(lb, LV_LABEL_LONG_WRAP);
                lv_obj_set_width(lb, LV_PCT(100));
                lv_obj_set_style_pad_bottom(lb, 8, 0);
            }
        }
    }
    if (a->diag_built_log != d->log_generation) {
        a->diag_built_log = d->log_generation;
        /* The list is replaced whole: at most DIAG_LOG_MAX entries of two
         * labels each, and never appended to. */
        lv_obj_clean(a->diag_log_box);
        for (i = 0; i < d->log_count; i++) {
            enum pos_style_role role = d->log[i].severity == DIAG_SEV_ERROR ? POS_STYLE_STATUS_ERROR_TEXT
                                       : d->log[i].severity == DIAG_SEV_WARN ? POS_STYLE_STATUS_WARN_TEXT
                                                                              : POS_STYLE_CAPTION;

            lb = pocketui_label(a->diag_log_box, d->log[i].head, POS_STYLE_CAPTION);
            if (role != POS_STYLE_CAPTION) {
                pos_style_add(lb, role, 0);
            }
            lv_obj_set_style_pad_top(lb, 12, 0);
            lb = pocketui_label(a->diag_log_box, d->log[i].message, POS_STYLE_TEXT_PRIMARY);
            lv_label_set_long_mode(lb, LV_LABEL_LONG_WRAP);
            lv_obj_set_width(lb, LV_PCT(100));
        }
    }
}

/* One step of a refresh: one call, bounded by the UI deadline. */
static void diag_step(struct system_app *a)
{
    char err[96] = "";
    cJSON *r = NULL;

    switch (diag_view_step(&a->dv)) {
    case DIAG_STEP_STATUS:
        r = shell_ipc_call_timeout("sysd", "system.status", NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                   sizeof(err));
        system_view_apply_status(&a->view, r, a->clock_ms);
        diag_view_apply_system(&a->dv, &a->view, r);
        break;
    case DIAG_STEP_RADIO:
        /* Not asked when the status bar's own poll already says radiod is
         * not answering: that would be a second 200 ms spent learning it. */
        r = pocketos_shell_radio_state()
                ? shell_ipc_call_timeout("radiod", "radio.status", NULL, SHELL_IPC_UI_TIMEOUT_MS,
                                         err, sizeof(err))
                : NULL;
        diag_view_apply_radio(&a->dv, r);
        break;
    case DIAG_STEP_MESH:
        r = shell_ipc_call_timeout("meshcored", "mesh.status", NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                   sizeof(err));
        diag_view_apply_mesh(&a->dv, r);
        break;
    case DIAG_STEP_CRASHES:
        r = shell_ipc_call_timeout("sysd", "system.crashes", NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                   sizeof(err));
        diag_view_apply_crashes(&a->dv, r);
        break;
    case DIAG_STEP_LOGS:
        r = shell_ipc_call_timeout("sysd", "system.logs", diag_view_logs_params(&a->dv),
                                   SHELL_IPC_UI_TIMEOUT_MS, err, sizeof(err));
        diag_view_apply_logs(&a->dv, r);
        break;
    case DIAG_STEP_IDLE:
    default:
        return;
    }
    cJSON_Delete(r);
    diag_view_step_done(&a->dv);
}

/* ---- building the body ------------------------------------------------- */

static void build_confirm(struct system_app *a)
{
    lv_obj_t *p = system_panel(a, SYSTEM_COL_LEFT);
    lv_obj_t *buttons;
    lv_obj_t *cancel;
    lv_obj_t *confirm;
    lv_obj_t *body;

    a->dialog = p;
    pocketui_label(p, system_view_dialog_title(&a->view), POS_STYLE_TITLE);
    body = pocketui_label(p, system_view_dialog_body(&a->view), POS_STYLE_TEXT_SECONDARY);
    lv_label_set_long_mode(body, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(body, LV_PCT(100));
    lv_obj_set_style_pad_top(body, 12, 0);
    lv_obj_set_style_pad_bottom(body, 20, 0);

    buttons = button_row(p);

    /* Cancel is first, and on a power-off it is also the accented one. This
     * panel is touch-only: there is no input group, so lv_group_focus_obj
     * below is a no-op on the device and the styling is the only thing that
     * says which choice is safe. Observed on unit A 2026-09-10, where the
     * accent sat on "Power off" - the one action that cannot be undone from a
     * desk was the one drawing the eye. */
    cancel = row_button(buttons, "Cancel", on_cancel, a);
    confirm = row_button(buttons, system_view_dialog_confirm_label(&a->view), on_confirm, a);
    restrain(system_view_dialog_emphasis(&a->view) == SYSTEM_VIEW_EMPHASIS_CANCEL ? confirm
                                                                                  : cancel);

    if (lv_group_get_default()) {
        lv_group_focus_obj(cancel);
    }
}

static void build_terminal(struct system_app *a)
{
    lv_obj_t *p = system_panel(a, SYSTEM_COL_LEFT);
    lv_obj_t *lb;

    a->dialog = p;
    lb = pocketui_label(p, system_view_terminal_text(&a->view), POS_STYLE_TITLE);
    lv_label_set_long_mode(lb, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(lb, LV_PCT(100));
}

/* OVERVIEW: the machine at a glance - vitals and storage side by side when
 * wide - and the two actions, last on the page and never under the thumb on
 * arrival. */
static void build_overview(struct system_app *a)
{
    const struct system_view *v = &a->view;
    lv_obj_t *p;
    lv_obj_t *r;
    lv_obj_t *buttons;
    lv_obj_t *poweroff;
    int i;

    p = system_panel(a, SYSTEM_COL_LEFT);
    for (i = 0; i < 3; i++) {
        r = vitals_row(p);
        a->vital[i * 2] = vitals_cell(r, v->vitals[i * 2].label);
        a->vital[i * 2 + 1] = vitals_cell(r, v->vitals[i * 2 + 1].label);
    }

    p = system_panel(a, SYSTEM_COL_RIGHT);
    system_section_caption(p, "STORAGE");
    if (v->mount_count == 0) {
        pocketui_label(p, "no mounts reported", POS_STYLE_TEXT_MUTED);
    }
    for (i = 0; i < v->mount_count && i < SYSTEM_VIEW_MAX_MOUNTS; i++) {
        lv_obj_t *cell = lv_obj_create(p);
        lv_obj_t *top;
        lv_obj_t *track;

        lv_obj_remove_style_all(cell);
        pos_style_add(cell, POS_STYLE_DIVIDER, 0);
        lv_obj_set_width(cell, LV_PCT(100));
        lv_obj_set_height(cell, SYSTEM_MOUNT_ROW_H);
        lv_obj_set_flex_flow(cell, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(cell, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START,
                              LV_FLEX_ALIGN_START);
        lv_obj_clear_flag(cell, LV_OBJ_FLAG_SCROLLABLE);

        top = lv_obj_create(cell);
        lv_obj_remove_style_all(top);
        lv_obj_set_width(top, LV_PCT(100));
        lv_obj_set_height(top, LV_SIZE_CONTENT);
        lv_obj_set_flex_flow(top, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(top, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                              LV_FLEX_ALIGN_CENTER);
        lv_obj_clear_flag(top, LV_OBJ_FLAG_SCROLLABLE);
        pocketui_label(top, v->mounts[i].mount, POS_STYLE_TEXT_SECONDARY);
        a->mount_detail[i] = pocketui_label(top, v->mounts[i].detail, POS_STYLE_VALUE);
        /* What the mount's name leaves, not a fixed 70 %: at a larger text
         * size the two ran into each other (DS §46.5). */
        pocketui_label_rest_of_row(a->mount_detail[i]);

        track = lv_obj_create(cell);
        lv_obj_remove_style_all(track);
        pos_style_add(track, POS_STYLE_SLAB, 0);
        lv_obj_set_width(track, LV_PCT(100));
        lv_obj_set_height(track, SYSTEM_METER_H);
        lv_obj_set_style_pad_all(track, 0, 0);
        lv_obj_clear_flag(track, LV_OBJ_FLAG_SCROLLABLE);
        a->mount_bar[i] = lv_obj_create(track);
        lv_obj_remove_style_all(a->mount_bar[i]);
        pos_style_add(a->mount_bar[i], POS_STYLE_BUTTON_PRIMARY, 0);
        lv_obj_set_height(a->mount_bar[i], SYSTEM_METER_H);
        lv_obj_align(a->mount_bar[i], LV_ALIGN_LEFT_MID, 0, 0);
        lv_obj_clear_flag(a->mount_bar[i], LV_OBJ_FLAG_SCROLLABLE);
    }

    /* The microSD card: how much of it is unused and the way to use it, or
     * how an expansion is going. Nothing at all when there is nothing to say. */
    if (v->expand_line[0] || v->expand == SYSTEM_VIEW_EXPAND_OFFER) {
        a->expand_line = system_wrap_label(p, v->expand_line, POS_STYLE_TEXT_SECONDARY);
    }
    if (v->expand == SYSTEM_VIEW_EXPAND_OFFER) {
        restrain(row_button(button_row(p), "Expand storage", on_expand, a));
    }

    p = system_panel(a, SYSTEM_COL_RIGHT);
    buttons = button_row(p);
    row_button(buttons, "Restart", on_restart, a);
    /* Power off is the secondary action: on this board it cannot be undone
     * from here (docs/hardware/V0.0.7_BLOCK2C_SMOKE.md). */
    poweroff = row_button(buttons, "Power off", on_poweroff, a);
    restrain(poweroff);
}

/* SERVICES: what runs, and the way into Diagnostics (diag_view.h). */
static void build_services(struct system_app *a)
{
    const struct system_view *v = &a->view;
    lv_obj_t *p = system_panel(a, SYSTEM_COL_LEFT);
    lv_obj_t *r;
    lv_obj_t *lb;
    lv_obj_t *buttons;
    int i;

    system_section_caption(p, "SERVICES");
    if (v->service_count == 0) {
        pocketui_label(p, "no services reported", POS_STYLE_TEXT_MUTED);
    }
    for (i = 0; i < v->service_count && i < SYSTEM_VIEW_MAX_SERVICES; i++) {
        r = system_row(p, POCKETUI_ROW_H);
        system_row_may_wrap(r);
        lb = pocketui_label(r, v->services[i].name, POS_STYLE_TEXT_SECONDARY);
        lv_label_set_long_mode(lb, LV_LABEL_LONG_DOT);
        lv_obj_set_style_max_width(lb, LV_PCT(30), 0);
        a->svc_chip[i] = system_chip(r, service_chip_text(v->services[i].state),
                                     service_chip_role(v->services[i].state));
        a->svc_detail[i] = pocketui_label(r, v->services[i].detail, POS_STYLE_CAPTION);
        lv_label_set_long_mode(a->svc_detail[i], LV_LABEL_LONG_DOT);
        /* Wider than the name: a crash-looped service's detail is the only
         * thing on this row anybody needs, and it must not lose its tail.
         * As wide as it is while the row has room; past that, a line of its
         * own (system_row_may_wrap), never a fixed share cut with dots. */
        lv_obj_set_style_max_width(a->svc_detail[i], LV_PCT(100), 0);
    }

    /* Beside the list when wide, under it when tall. */
    p = system_panel(a, SYSTEM_COL_RIGHT);
    buttons = button_row(p);
    restrain(row_button(buttons, "Diagnostics", on_diagnostics, a));
}

/* ABOUT: what this device and this build are, from system.info, asked for
 * once. Nothing on this page changes while it is up. Doors and the device
 * first; what they are built on beside them when wide. */
static void build_about(struct system_app *a)
{
    const struct system_view *v = &a->view;
    lv_obj_t *p = system_panel(a, SYSTEM_COL_LEFT);

    identity_row(p, "Doors", v->os_version);
    if (v->show_card) {
        pocketui_kv_row(p, "Card", v->card_version);
    }
    pocketui_kv_row(p, "Model", v->model);
    pocketui_kv_row(p, "Kernel", v->kernel);
    p = system_panel(a, SYSTEM_COL_RIGHT);
    pocketui_kv_row(p, "Platform", v->platform);
    pocketui_kv_row(p, "Vendor SDK", v->sdk);
    pocketui_kv_row(p, "CPUs", v->cpus);
}

/* ---- the layout -------------------------------------------------------- *
 *
 * The screen sits in one frame that is exactly the body's content box - the
 * whole of the room the shell gives the app - and is arranged from the size
 * of that box alone:
 *
 *   TALL (portrait: 528 x 1060 on the reference panel). The tabs, the
 *   freshness line, then the page's panels one above the other.
 *
 *   WIDE (landscape: 1192 x 396). The tabs with the freshness line at the
 *   end of their row, and the page's two columns side by side with the DS 7
 *   panel gap between them: the machine's vitals beside storage and the
 *   actions, the interfaces beside the links. A page with one column (the
 *   services, the identity) keeps it across the body. A confirmation, or
 *   the panel a power action leaves, keeps its
 *   portrait width, centred, with the freshness line over it at the same
 *   width (DS 23.4). Chosen only when each half keeps SYSTEM_COLUMN_W, so no
 *   panel, row or button is narrower than in portrait. No control takes its
 *   size from the height, so no body can bring one under its DS 7 size.
 *
 * In either shape the page itself is the one box that scrolls, and only when
 * what it holds is taller than the room: nothing inside it scrolls (DS
 * §52.2; v0.0.10 to v0.3.0 had a column for each half that scrolled on its
 * own in landscape).
 *
 * The body is built as it always was - when what it holds changes shape - and
 * arranged when it is built. A change of the frame's size only arranges: flow
 * and widths. The objects, their values, the phase and a refused action's
 * reason are not touched by it.
 *
 * Whatever the shape, nothing is drawn into the panel's unsafe area (DS 21.1,
 * 22.2): a scrolled page passes the foot of the body, which reaches 10 px into
 * the 30 px corner squares of the reference panel, so the frame pads its foot
 * by however far a corner square reaches into the body, from the platform's
 * description (pos_display_rect_insets, the rule Calculator and Notes use).
 * On a panel with square corners the pad is 0. */

/* Tall: the tabs, the freshness line under them, and one column. Wide: the
 * freshness line at the end of the tabs' row, and the two columns side by
 * side - or the one, across. */
/* The tabs share their row while their words fit it, each an equal share of
 * it; when the text size makes the widest of the four wider than its share
 * (Medium and Large in portrait), they go two to a line, each half the row,
 * rather than squeeze a word past its button's edge. Measured from the words
 * and the fonts, not from anything laid out, so it holds inside a layout
 * pass. */
static void arrange_tabs(struct system_app *a)
{
    int32_t widest = 0;
    bool pairs;
    int i;

    if (a->full_w <= 0) {
        return; /* not laid out yet: the first layout pass arranges them */
    }
    for (i = 0; i < SYSTEM_TAB_COUNT; i++) {
        lv_obj_t *b = a->tab_btn[i];
        lv_obj_t *lb = b ? lv_obj_get_child(b, 0) : NULL;
        lv_point_t size;

        if (!lb) {
            return;
        }
        lv_text_get_size(&size, lv_label_get_text(lb), lv_obj_get_style_text_font(lb, LV_PART_MAIN),
                         lv_obj_get_style_text_letter_space(lb, LV_PART_MAIN), 0, LV_COORD_MAX, LV_TEXT_FLAG_NONE);
        size.x += lv_obj_get_style_pad_left(b, LV_PART_MAIN) + lv_obj_get_style_pad_right(b, LV_PART_MAIN) +
                  2 * lv_obj_get_style_border_width(b, LV_PART_MAIN) + 4;
        widest = LV_MAX(widest, size.x);
    }
    pairs = SYSTEM_TAB_COUNT * widest + (SYSTEM_TAB_COUNT - 1) * 8 > a->full_w;
    for (i = 0; i < SYSTEM_TAB_COUNT; i++) {
        lv_obj_set_flex_grow(a->tab_btn[i], pairs ? 0 : 1);
        lv_obj_set_width(a->tab_btn[i], pairs ? (a->full_w - 8) / 2 : LV_SIZE_CONTENT);
    }
}

static void arrange_live(struct system_app *a)
{
    bool two;

    arrange_tabs(a);
    lv_obj_set_flex_flow(a->body, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(a->body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    if (a->freshness && lv_obj_get_parent(a->freshness) == a->tabs) {
        lv_obj_set_width(a->freshness, a->wide ? LV_SIZE_CONTENT : LV_PCT(100));
        lv_obj_set_style_min_width(a->freshness, a->wide ? 96 : 0, 0);
    }
    if (!a->cols) {
        return;
    }
    two = lv_obj_get_child_count(a->col[1]) > 0;
    lv_obj_set_flex_flow(a->cols, a->wide ? LV_FLEX_FLOW_ROW : LV_FLEX_FLOW_COLUMN);
    lv_obj_set_width(a->col[0], a->wide && two ? a->half_w : LV_PCT(100));
    lv_obj_set_width(a->col[1], a->wide ? a->half_w : LV_PCT(100));
    if (two) {
        lv_obj_clear_flag(a->col[1], LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_add_flag(a->col[1], LV_OBJ_FLAG_HIDDEN);
    }
}

/* Across the body when tall; the portrait width, centred, when wide, the
 * freshness line over it at the same width. The body scrolls in either. */
static void arrange_dialog(struct system_app *a)
{
    int32_t w = a->wide ? SYSTEM_COLUMN_W : LV_PCT(100);
    lv_flex_align_t across = a->wide ? LV_FLEX_ALIGN_CENTER : LV_FLEX_ALIGN_START;

    /* The body's one track is as wide as the widest of the two, so it is the
     * track that is centred, and the two in it. */
    lv_obj_set_flex_flow(a->body, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(a->body, LV_FLEX_ALIGN_START, across, across);
    lv_obj_set_width(a->dialog, w);
    if (a->freshness_row) {
        lv_obj_set_width(a->freshness_row, w);
    }
}

static void arrange(struct system_app *a)
{
    if (!a->body) {
        return;
    }
    if (a->diag) {
        /* One column in either shape: log lines are better read across the
         * whole width than squeezed into half of it. */
        lv_obj_set_flex_flow(a->body, LV_FLEX_FLOW_COLUMN);
        return;
    }
    if (a->dialog) {
        arrange_dialog(a);
    } else {
        arrange_live(a);
    }
}

static void layout(struct system_app *a)
{
    struct pos_insets in;
    const lv_area_t *box;
    int32_t w;
    int32_t h;

    /* Nothing to lay out in, or nothing the layout is chosen from has
     * changed: PocketUI owns that decision for every responsive app, and
     * hands back the corner clearance the platform rule gives this box. */
    if (!pocketui_layout_begin(&a->layout_guard, a->frame, &in)) {
        return;
    }
    box = &a->layout_guard.area;
    lv_obj_set_style_pad_left(a->frame, in.left, 0);
    lv_obj_set_style_pad_top(a->frame, in.top, 0);
    lv_obj_set_style_pad_right(a->frame, in.right, 0);
    lv_obj_set_style_pad_bottom(a->frame, in.bottom, 0);
    w = lv_area_get_width(box) - in.left - in.right;
    h = lv_area_get_height(box) - in.top - in.bottom;
    a->wide = w > h && w >= 2 * SYSTEM_COLUMN_W + SYSTEM_PANEL_GAP;
    a->full_w = w;
    a->half_w = (w - SYSTEM_PANEL_GAP) / 2;
    arrange(a);
}

/* The frame is the body's content box, so this is the body changing size:
 * the display turned under the open app, or this is the first layout pass
 * after the app was built. */
static void on_frame_size(lv_event_t *e)
{
    layout(lv_event_get_user_data(e));
}

static void build_frame(struct system_app *a)
{
    lv_obj_t *frame = lv_obj_create(a->root);

    lv_obj_remove_style_all(frame);
    /* Exactly the body's content box, whatever is in it, so the shape is
     * always chosen from the room the shell gives and never from the size of
     * what the arrangement itself put there. */
    lv_obj_set_size(frame, LV_PCT(100), LV_PCT(100));
    lv_obj_clear_flag(frame, LV_OBJ_FLAG_SCROLLABLE);
    a->frame = frame;
}

/* The body is rebuilt only when its shape changes - another page, a service
 * appearing, the card row starting to disagree, a dialog opening - and
 * repainted in place every other second otherwise, so a scroll position
 * survives a poll. */
static void rebuild(struct system_app *a)
{
    const struct system_view *v = &a->view;

    if (a->body) {
        lv_obj_delete(a->body);
    }
    a->tabs = NULL;
    memset(a->tab_btn, 0, sizeof(a->tab_btn));
    a->cols = NULL;
    memset(a->col, 0, sizeof(a->col));
    a->freshness_row = NULL;
    a->dialog = NULL;
    memset(a->vital, 0, sizeof(a->vital));
    memset(a->mount_detail, 0, sizeof(a->mount_detail));
    memset(a->mount_bar, 0, sizeof(a->mount_bar));
    a->expand_line = NULL;
    memset(a->svc_chip, 0, sizeof(a->svc_chip));
    memset(a->svc_detail, 0, sizeof(a->svc_detail));
    memset(&a->net, 0, sizeof(a->net));
    a->freshness = NULL;
    a->toast = NULL;
    memset(a->diag_value, 0, sizeof(a->diag_value));
    memset(a->diag_filter, 0, sizeof(a->diag_filter));
    a->diag_state = NULL;
    a->diag_crash_box = NULL;
    a->diag_log_box = NULL;
    a->diag_log_status = NULL;

    a->body = lv_obj_create(a->frame);
    lv_obj_remove_style_all(a->body);
    lv_obj_set_width(a->body, LV_PCT(100));
    lv_obj_set_height(a->body, LV_PCT(100));
    lv_obj_set_flex_flow(a->body, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(a->body, SYSTEM_PANEL_GAP, 0);
    lv_obj_set_style_pad_column(a->body, SYSTEM_PANEL_GAP, 0);
    lv_obj_set_scroll_dir(a->body, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(a->body, LV_SCROLLBAR_MODE_AUTO);

    if (a->diag && v->phase == SYSTEM_VIEW_LIVE) {
        build_diag(a);
    } else if (v->phase == SYSTEM_VIEW_TERMINAL_REBOOT || v->phase == SYSTEM_VIEW_TERMINAL_POWEROFF) {
        /* Nothing is being polled any more, so there is no freshness to
         * report and claiming one would be a lie. */
        build_terminal(a);
    } else if (v->phase == SYSTEM_VIEW_CONFIRM_REBOOT || v->phase == SYSTEM_VIEW_CONFIRM_POWEROFF ||
               v->phase == SYSTEM_VIEW_CONFIRM_EXPAND) {
        build_freshness(a);
        build_confirm(a);
    } else {
        int i;

        build_tabs(a);
        /* toast: the reason a refused action gave, above the page */
        a->toast = system_wrap_label(a->body, "", POS_STYLE_STATUS_ERROR_TEXT);
        lv_obj_add_flag(a->toast, LV_OBJ_FLAG_HIDDEN);
        a->cols = stack(a->body);
        for (i = 0; i < 2; i++) {
            a->col[i] = stack(a->cols);
        }
        switch (a->tab) {
        case SYSTEM_TAB_NETWORK:
            system_net_build(a);
            break;
        case SYSTEM_TAB_SERVICES:
            build_services(a);
            break;
        case SYSTEM_TAB_ABOUT:
            build_about(a);
            break;
        case SYSTEM_TAB_OVERVIEW:
        default:
            build_overview(a);
            break;
        }
    }
    a->built_mounts = v->mount_count;
    a->built_ifaces = v->iface_count;
    a->built_services = v->service_count;
    a->built_card = v->show_card;
    a->built_phase = v->phase;
    a->built_expand = v->expand;
    a->built_diag = a->diag;
    a->built_tab = a->tab;
    arrange(a);
    repaint(a);
    diag_repaint(a);
}

static int shape_changed(const struct system_app *a)
{
    const struct system_view *v = &a->view;

    return a->built_mounts != v->mount_count || a->built_ifaces != v->iface_count ||
           a->built_services != v->service_count || a->built_card != v->show_card ||
           a->built_phase != v->phase || a->built_diag != a->diag || a->built_tab != a->tab ||
           a->built_expand != v->expand;
}

/* ---- app lifecycle ----------------------------------------------------- */

static void poll_status(struct system_app *a)
{
    char err[96];
    cJSON *st;

    err[0] = '\0';
    st = shell_ipc_call_timeout("sysd", "system.status", NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                sizeof(err));
    system_view_apply_status(&a->view, st, a->clock_ms);
    if (st) {
        cJSON_Delete(st);
    }
    /* The card's expansion is shown on OVERVIEW only, so it is asked for
     * only there: a second bounded call, every other second. */
    if (a->tab == SYSTEM_TAB_OVERVIEW) {
        err[0] = '\0';
        st = shell_ipc_call_timeout("sysd", "storage.status", NULL, SHELL_IPC_UI_TIMEOUT_MS, err, sizeof(err));
        system_view_apply_storage(&a->view, st);
        cJSON_Delete(st);
    }
}

static void *system_create(lv_obj_t *root)
{
    struct system_app *a = calloc(1, sizeof(*a));
    char err[96];
    cJSON *info;

    if (!a) {
        return NULL;
    }
    a->root = root;
    system_view_init(&a->view);
    diag_view_init(&a->dv);
#if defined(POCKETOS_SHELL_TEST_HOOKS) && POCKETOS_SHELL_TEST_HOOKS
    {
        /* Simulator only: open on another tab, so a screenshot taken at
         * start shows it (tests/system_brand_shell_test.sh: the identity row
         * is on ABOUT). Compiled out of the panel's build. */
        const char *t = getenv("POCKETOS_TEST_SYSTEM_TAB");
        int i;

        for (i = 0; t && i < SYSTEM_TAB_COUNT; i++) {
            if (strcasecmp(t, tab_labels[i]) == 0) {
                a->tab = (enum system_tab)i;
            }
        }
    }
#endif

    /* Identity does not change while the system runs, so it is asked for once
     * and kept. A failure leaves it unknown rather than wrong; the next
     * screen visit asks again. */
    err[0] = '\0';
    info = shell_ipc_call_timeout("sysd", "system.info", NULL, SHELL_IPC_UI_TIMEOUT_MS, err,
                                  sizeof(err));
    system_view_apply_info(&a->view, info);
    if (info) {
        cJSON_Delete(info);
    }
    /* Region and backend are static too: one call, not a second poll. Skipped
     * entirely when the shell's own poll says radiod is not answering - there
     * is nothing to learn, and three bounded calls in a row on the LVGL
     * thread is 600 ms of no repaint on the one day every service is down. */
    err[0] = '\0';
    info = pocketos_shell_radio_state()
               ? shell_ipc_call_timeout("radiod", "radio.info", NULL, SHELL_IPC_UI_TIMEOUT_MS,
                                        err, sizeof(err))
               : NULL;
    if (info) {
        const cJSON *region = cJSON_GetObjectItemCaseSensitive(info, "region");
        const cJSON *backend = cJSON_GetObjectItemCaseSensitive(info, "backend");

        system_view_set_radio_detail(&a->view,
                                     cJSON_IsString(region) ? region->valuestring : NULL,
                                     cJSON_IsString(backend) ? backend->valuestring : NULL);
        cJSON_Delete(info);
    }
    system_view_set_radio_state(&a->view, pocketos_shell_radio_state());

    poll_status(a);
    build_frame(a);
    rebuild(a);
    /* Only now: building lays objects out as it goes, and the layout step
     * arranges objects that must all exist. */
    lv_obj_add_event_cb(a->frame, on_frame_size, LV_EVENT_SIZE_CHANGED, a);
    lv_obj_update_layout(a->frame);
    layout(a);
    return a;
}

static void system_tick(void *priv)
{
    struct system_app *a = priv;

    a->clock_ms += 1000;
    /* A machine that is on its way down has nothing left to report, and
     * asking a service that is being stopped only produces a timeout. */
    if (!system_view_is_polling(&a->view)) {
        return;
    }
    /* The radio state is whatever the status bar's own poll last saw. */
    system_view_set_radio_state(&a->view, pocketos_shell_radio_state());
    if (a->diag) {
        /* The page asks for what it shows, one call a tick, and nothing
         * else is polled meanwhile. */
        diag_step(a);
        diag_repaint(a);
        return;
    }
    if (a->tab == SYSTEM_TAB_ABOUT) {
        /* Nothing on it is live. */
        return;
    }
    if (++a->tick >= SYSTEM_POLL_TICKS) {
        a->tick = 0;
        poll_status(a);
    } else {
        /* No poll this second, but the age of the last one still moves. */
        system_view_refresh_freshness(&a->view, a->clock_ms);
    }
    if (a->tab == SYSTEM_TAB_NETWORK) {
        system_net_poll_step(a);
    }
    if (shape_changed(a)) {
        rebuild(a);
    } else {
        repaint(a);
    }
}

static void system_destroy(void *priv)
{
    struct system_app *a = priv;

    /* The frame outlives this by a moment, until the shell deletes the app's
     * objects; nothing may call back into a freed app in between. */
    if (a) {
        lv_obj_remove_event_cb_with_user_data(a->frame, on_frame_size, a);
    }
    free(priv);
}

LV_IMAGE_DECLARE(pos_app_icon_system);

/* The Back action and the header's back slab (app.h `back`,
 * `back_slab_in_app`): Diagnostics closes as its own Back button closes it,
 * back to SERVICES. The tabs are one level, so from any of them Back is the
 * shell's: to Settings, whose page System is (DS §47). */
static int system_back(void *priv)
{
    struct system_app *a = priv;

    if (!a || !a->diag) {
        return 0;
    }
    a->diag = false;
    rebuild(a);
    return 1;
}

const struct pocketos_app app_system = {
    .id = "system",
    .name = "System",
    .icon = LV_SYMBOL_SETTINGS,
    .icon_mask = &pos_app_icon_system,
    .create = system_create,
    .tick = system_tick,
    .destroy = system_destroy,
    .back = system_back,
    .back_slab_in_app = true,
};
