/*
 * Thirty more games for tests/home_folder_test.c: rows of the launcher's table
 * (ui/shell/home_layout.c, HOME_LAYOUT_TEST_ENTRIES_FILE), all in GAMES.
 *
 * Copyright (c) 2026 PocketOS authors.
 * SPDX-License-Identifier: Apache-2.0
 */
{ "g01", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g02", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g03", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g04", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g05", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g06", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g07", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g08", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g09", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g10", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g11", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g12", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g13", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g14", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g15", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g16", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g17", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g18", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g19", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g20", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g21", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g22", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g23", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g24", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g25", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g26", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g27", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g28", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g29", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
{ "g30", HOME_GROUP_FOLDERS, HOME_HUE_GAMES, HOME_FOLDER_GAMES },
