#!/bin/bash
# Doors is Apache-2.0 (ADR-013), and not everything in this repository is.
# This audit keeps the two apart, reading the tracked files themselves:
#
#   - Every SPDX-License-Identifier in a tracked source file is a well-formed
#     licence expression, and on first-party material it says Apache-2.0.
#   - No Apache-2.0 SPDX line sits where the material is not the project's to
#     license: third_party/, docs/legal/, the kernel patches, the supplied
#     design packages, the IBM Plex bitmap fonts, and generated files (their
#     licence follows their inputs).
#   - The pre-licence pointer "License: see LICENSE (TBD)" is gone.
#   - Every first-party source file carries the SPDX line, or is listed with
#     a reason in docs/licensing/spdx-exempt.txt.
#   - Everything third_party/notices/SOURCES ships from others has a row in
#     THIRD_PARTY_LICENSES.md.
#   - No model file is committed. A model the package installs has a row in
#     MODEL_LICENSES.md and a notices entry, and one whose status there is
#     UNKNOWN is installed only if it is the one the owner allowed for
#     internal images; an EXTERNAL ONLY model is never installed. These rules
#     are executed against scratch packages that break them, not only read.
#
# Copyright (c) 2026 PocketOS authors.
# SPDX-License-Identifier: Apache-2.0
set -u
cd "$(dirname "$0")/.." || exit 1
failed=0
check() { if [ "$2" = "1" ]; then echo "ok   $1"; else echo "FAIL $1"; failed=$((failed + 1)); fi; }
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# A gate that cannot see the files must not report success
# (tests/required_gates_test.sh explains why).
if ! git ls-files > "$TMP/files" 2>/dev/null || [ ! -s "$TMP/files" ]; then
    echo "license_audit_test: NOT RUN - it reads the tracked files and git cannot list them here"
    exit 1
fi

TAG='SPDX-License-'"Identifier"   # split so this file does not match itself
EXEMPT=docs/licensing/spdx-exempt.txt
MK=platforms/k230/package/pocketos/pocketos.mk
SOURCES=third_party/notices/SOURCES
TPL=THIRD_PARTY_LICENSES.md
MODELS=MODEL_LICENSES.md

# Where an Apache-2.0 tag must never be, as extended regexes on the path.
NOT_OURS='^(third_party/|docs/legal/|vendor/|platforms/k230/patches/|docs/design/brand/|docs/design/rift/|ui/pocketui/fonts/|THIRD_PARTY_NOTICES\.txt$)'
# First-party source: what the header rule applies to.
FIRST_PARTY_SRC='^(apps|core|services|protocols|tools|ui|tests)/.*\.(c|h|cpp|hpp|sh|py|js|ps1)$|^platforms/k230/scripts/[^/]+\.sh$|^platforms/k230/rootfs_overlay/etc/init\.d/S[0-9]+[a-z0-9-]+$|^Makefile$|(^|/)CMakeLists\.txt$'

# ---- SPDX lines --------------------------------------------------------------
# path<TAB>value for every tag in a non-Markdown file (prose may quote the tag).
git grep -I -o -E "${TAG}:[[:space:]]*[^*]*" -- ':!*.md' 2>/dev/null |
    sed -e "s/:${TAG}:[[:space:]]*/	/" -e 's/[[:space:]]*\(\*\/\|-->\)\{0,1\}[[:space:]]*$//' > "$TMP/tags"
check "the tags could be read (the scan found this file's own)" \
    "$(grep -q -x -F "tests/license_audit_test.sh	Apache-2.0" "$TMP/tags" && echo 1 || echo 0)"
exempt() { grep -v -E '^[[:space:]]*(#|$)' "$EXEMPT" 2>/dev/null | awk '{print $1}' | sort -u; }

# SPDX licence-expression syntax, simple form: ids joined by AND, OR, WITH.
bad=$(awk -F '\t' '$2 !~ /^[A-Za-z0-9.+-]+( (AND|OR|WITH) [A-Za-z0-9.+-]+)*$/ {print $1": "$2}' "$TMP/tags")
check "every SPDX line is a well-formed licence expression${bad:+ (not: $bad)}" "$([ -z "$bad" ] && echo 1 || echo 0)"

# Apache-2.0 tags where the material is not the project's to license.
misplaced() { # <tags file>
    awk -F '\t' '$2 ~ /(^|[ (])Apache-2\.0($|[ )])/ {print $1}' "$1" | grep -E "$NOT_OURS" | sort -u
}
# Apache-2.0 tags on generated files: their licence follows their inputs.
generated() { # <tags file>
    awk -F '\t' '$2 ~ /Apache-2\.0/ {print $1}' "$1" | sort -u | while IFS= read -r f; do
        head -3 "$f" 2>/dev/null | grep -q -i -E 'generated by|do not edit' && printf '%s\n' "$f"
    done
}
hits=$(misplaced "$TMP/tags")
check "no Apache-2.0 SPDX line on third-party, legal, patch, supplied-design or font material${hits:+ (found: $hits)}" \
    "$([ -z "$hits" ] && echo 1 || echo 0)"
gen=$(generated "$TMP/tags")
check "and none on a generated file${gen:+ (found: $gen)}" "$([ -z "$gen" ] && echo 1 || echo 0)"
# Controls: the same two rules, on tags that break them.
printf '/* Generated by x. Do not edit. */\n' > "$TMP/gen.c"
printf 'platforms/k230/patches/linux/0099-x.patch\tApache-2.0\nthird_party/notices/texts/x.txt\tMIT OR Apache-2.0\n%s\tApache-2.0\n' \
    "$TMP/gen.c" > "$TMP/badtags"
check "the placement rule refuses a tag on a kernel patch and on a notices text (control)" \
    "$([ "$(misplaced "$TMP/badtags" | wc -l)" = 2 ] && echo 1 || echo 0)"
check "and the generated-file rule a tag on a generated file (control)" \
    "$([ "$(generated "$TMP/badtags")" = "$TMP/gen.c" ] && echo 1 || echo 0)"

grep -E "$FIRST_PARTY_SRC" "$TMP/files" | grep -v -E "$NOT_OURS" | sort -u > "$TMP/fp"
exempt > "$TMP/exempt"
# A first-party file that is partly someone else's says so with a compound
# expression (Apache-2.0 AND MIT) and is on the exemption list with the reason.
other=$(awk -F '\t' 'NR == FNR {fp[$1] = 1; next} ($1 in fp) && $2 != "Apache-2.0" {print $1}' "$TMP/fp" "$TMP/tags" |
        sort -u | comm -23 - "$TMP/exempt" | tr '\n' ' ')
check "first-party sources that carry a tag say Apache-2.0, unless listed as mixed${other:+ (other: $other)}" \
    "$([ -z "$other" ] && echo 1 || echo 0)"
mixed=$(awk -F '\t' 'NR == FNR {fp[$1] = 1; next} ($1 in fp) && $2 != "Apache-2.0" && $2 !~ /^Apache-2\.0 AND / {print $1": "$2}' \
        "$TMP/fp" "$TMP/tags")
check "and a mixed one still names Apache-2.0 for the project's part${mixed:+ (not: $mixed)}" \
    "$([ -z "$mixed" ] && echo 1 || echo 0)"

tbd=$(git grep -l -F 'License: see LICENSE (TBD)' -- . ':!docs/' ':!tests/license_audit_test.sh' 2>/dev/null)
check "no file still points to the undecided licence${tbd:+ (still: $(printf '%s' "$tbd" | tr '\n' ' '))}" \
    "$([ -z "$tbd" ] && echo 1 || echo 0)"

# ---- every first-party source file has its header ---------------------------
awk -F '\t' '$2 == "Apache-2.0" {print $1}' "$TMP/tags" | sort -u > "$TMP/apache"
missing=$(comm -23 "$TMP/fp" "$TMP/apache" | comm -23 - "$TMP/exempt" | tr '\n' ' ')
check "every first-party source file carries the Apache-2.0 SPDX line or is listed with a reason${missing:+ (missing: $missing)}" \
    "$([ -z "$missing" ] && echo 1 || echo 0)"
stale=""
for f in $(cat "$TMP/exempt"); do grep -qx -F "$f" "$TMP/files" || stale="$stale $f"; done
check "the exemption list names only tracked files${stale:+ (gone:$stale)}" "$([ -z "$stale" ] && echo 1 || echo 0)"
noreason=$(grep -v -E '^[[:space:]]*(#|$)' "$EXEMPT" 2>/dev/null | awk 'NF < 2 {print $1}')
check "and gives a reason for each${noreason:+ (no reason: $noreason)}" "$([ -z "$noreason" ] && echo 1 || echo 0)"

# ---- the root files -----------------------------------------------------------
check "LICENSE, NOTICE, THIRD_PARTY_LICENSES.md and MODEL_LICENSES.md are tracked" \
    "$(for f in LICENSE NOTICE "$TPL" "$MODELS"; do grep -qx -F "$f" "$TMP/files" || exit 1; done; echo 1)"
ids=$(grep -v -E '^[[:space:]]*(#|$)' "$SOURCES" | awk -F ' [|] ' '{print $1}' | sed 's/[[:space:]]*$//')
absent=""
for i in $ids; do grep -q -F "\`$i\`" "$TPL" || absent="$absent $i"; done
check "every component the notices ship has a row in THIRD_PARTY_LICENSES.md${absent:+ (absent:$absent)}" \
    "$([ -z "$absent" ] && echo 1 || echo 0)"
# The Canaan SDK licence (pos-vision's libmmz and adapted samples) is a copy
# kept here with its CRLF line ends made LF. Compared where the pinned SDK is
# checked out; its entry must name the SDK commit the build pins.
CANAAN=docs/legal/third-party/canaan-k230-linux-sdk-LICENSE.txt
SDKLIC=vendor/T-Display-K230/k230_linux_sdk/LICENSE
if [ -f "$SDKLIC" ]; then
    check "the Canaan licence copy is the pinned SDK's LICENSE, line ends aside" \
        "$(tr -d '\r' < "$SDKLIC" | cmp -s - "$CANAAN" && echo 1 || echo 0)"
fi
check "and its notices entry names the SDK commit the build pins" \
    "$(grep -q "^canaan-k230-sdk [|] .*SDK commit $(tr -d '\r\n' < platforms/k230/vendor_sdk_commit.txt) " "$SOURCES" && echo 1 || echo 0)"
# Files that adapt MeshCore or the Canaan samples name that licence too.
for pair in "MIT:third_party/notices/texts/meshcore.txt" "BSD-2-Clause:$CANAAN"; do
    lic=${pair%%:*}; text=${pair#*:}
    n=$(awk -F '\t' -v l="$lic" '$2 == "Apache-2.0 AND " l {print $1}' "$TMP/tags" | sort -u)
    bad=""
    for f in $n; do grep -q -F "$text" "$f" || bad="$bad $f"; done
    check "files tagged Apache-2.0 AND $lic point to that licence's text${bad:+ (not:$bad)}" "$([ -z "$bad" ] && echo 1 || echo 0)"
done

# ---- models ------------------------------------------------------------------
committed=$(grep -i -E '\.(kmodel|onnx|tflite|pt|pth|safetensors|gguf|caffemodel|weights)$' "$TMP/files")
check "no model file is committed${committed:+ (found: $committed)}" "$([ -z "$committed" ] && echo 1 || echo 0)"

# The rows of MODEL_LICENSES.md's matrix that name a Doors model path.
model_row() { grep -F "\`/usr/share/doors/vision/$1\`" "$2" | head -1; }
# Model files a package file installs into the image: names under
# usr/share/doors/vision/ on its install lines.
installed_models() { # <package .mk> <Makefile>
    cat "$@" | grep -E '\$\((INSTALL|TARGET_DIR)\)|^\s+install ' |
        grep -o -E 'usr/share/doors/vision/[A-Za-z0-9_.-]+' | sed 's#.*/##' | sort -u
}
# The only UNKNOWN-status model allowed into an image: decided by the owner for
# internal images (docs/LICENSING.md item 10), with its notice.
INTERNAL_OK="yolov8n.kmodel:yolov8n-kmodel"
model_rules() { # <package .mk> <Makefile> <MODEL_LICENSES.md> <SOURCES>; prints each violation
    local m row allowed note
    for m in $(installed_models "$1" "$2"); do
        row=$(model_row "$m" "$3")
        [ -n "$row" ] || { echo "$m installed but not in MODEL_LICENSES.md"; continue; }
        case "$row" in *"EXTERNAL ONLY"*) case "$row" in *UNKNOWN*"internal images only"*|*"internal images only"*UNKNOWN*) ;; *)
            echo "$m is EXTERNAL ONLY but installed"; continue ;; esac ;; esac
        case "$row" in
            *UNKNOWN*)
                allowed=""
                for a in $INTERNAL_OK; do [ "${a%%:*}" = "$m" ] && allowed="${a#*:}"; done
                if [ -z "$allowed" ]; then echo "$m has status UNKNOWN and is installed"
                else
                    printf '%s\n' "$row" | grep -q 'internal images only' || echo "$m: its row does not say internal images only"
                    grep -q "^${allowed} *|" "$4" || echo "$m: no notices entry ${allowed}"
                fi ;;
        esac
    done
}
v=$(model_rules "$MK" Makefile "$MODELS" "$SOURCES")
check "every installed model is listed, and none of unknown terms is installed but the internal-only one${v:+ ($v)}" \
    "$([ -z "$v" ] && echo 1 || echo 0)"
check "the package does install that one (the rule above is not vacuous)" \
    "$(installed_models "$MK" Makefile | grep -qx yolov8n.kmodel && echo 1 || echo 0)"
ext=$(grep -F 'EXTERNAL ONLY' "$MODELS" | grep -o -E '`/usr/share/doors/vision/[A-Za-z0-9_.-]+`' | tr -d '`' | sed 's#.*/##' | sort -u)
check "MODEL_LICENSES.md names the EXTERNAL ONLY models (face_det, text_det, text_rec, text_dict, face_embed)" \
    "$([ "$(printf '%s\n' $ext | tr '\n' ' ')" = 'face_det.kmodel face_embed.kmodel text_det.kmodel text_dict.txt text_rec.kmodel ' ] && echo 1 || echo 0)"
# Executed against packages that break the rules.
cp "$MK" "$TMP/ext.mk"
printf '\t$(INSTALL) -D -m 0644 x/face_det.kmodel $(TARGET_DIR)/usr/share/doors/vision/face_det.kmodel\n' >> "$TMP/ext.mk"
check "a package that installs an EXTERNAL ONLY model is refused (control)" \
    "$(model_rules "$TMP/ext.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'face_det.kmodel' && echo 1 || echo 0)"
cp "$MK" "$TMP/new.mk"
printf '\t$(INSTALL) -D -m 0644 x/mystery.kmodel $(TARGET_DIR)/usr/share/doors/vision/mystery.kmodel\n' >> "$TMP/new.mk"
check "and so is one that installs a model MODEL_LICENSES.md does not list (control)" \
    "$(model_rules "$TMP/new.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'mystery.kmodel installed but not in' && echo 1 || echo 0)"
grep -v '^yolov8n-kmodel ' "$SOURCES" > "$TMP/SOURCES"
check "and the internal-only model without its notices entry (control)" \
    "$(model_rules "$MK" Makefile "$MODELS" "$TMP/SOURCES" | grep -q 'no notices entry' && echo 1 || echo 0)"

echo "license_audit_test: $failed failure(s)"
exit $((failed > 0))
