#!/bin/bash
# Doors is Apache-2.0 (ADR-013), and not everything in this repository is.
# This audit keeps the two apart, reading the tracked files themselves:
#
#   - Every SPDX-License-Identifier in a tracked source file is a well-formed
#     licence expression, and on first-party material it says Apache-2.0.
#   - No Apache-2.0 SPDX line sits where the material is not the project's to
#     license: third_party/, docs/legal/, the kernel patches, the supplied
#     design packages, the IBM Plex bitmap fonts, and generated files (their
#     licence follows their inputs).
#   - The pre-licence pointer "License: see LICENSE (TBD)" is gone.
#   - Every first-party source file carries the SPDX line, or is listed with
#     a reason in docs/licensing/spdx-exempt.txt.
#   - Everything third_party/notices/SOURCES ships from others has a row in
#     THIRD_PARTY_LICENSES.md.
#   - No model file is committed. A model the package installs has a row in
#     MODEL_LICENSES.md; its status there is REDISTRIBUTABLE, or OWNER-LICENSED
#     with the notices its row names (R0, 0.3.6, Apache-2.0), and
#     one whose status is UNKNOWN is installed only if it is the one the owner
#     allowed for internal images; an EXTERNAL ONLY model is never installed.
#     These rules are executed against scratch packages that break them, not
#     only read.
#
# Copyright (c) 2026 PocketOS authors.
# SPDX-License-Identifier: Apache-2.0
set -u
cd "$(dirname "$0")/.." || exit 1
failed=0
check() { if [ "$2" = "1" ]; then echo "ok   $1"; else echo "FAIL $1"; failed=$((failed + 1)); fi; }
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# A gate that cannot see the files must not report success
# (tests/required_gates_test.sh explains why).
if ! git ls-files > "$TMP/files" 2>/dev/null || [ ! -s "$TMP/files" ]; then
    echo "license_audit_test: NOT RUN - it reads the tracked files and git cannot list them here"
    exit 1
fi

TAG='SPDX-License-'"Identifier"   # split so this file does not match itself
EXEMPT=docs/licensing/spdx-exempt.txt
MK=platforms/k230/package/pocketos/pocketos.mk
SOURCES=third_party/notices/SOURCES
TPL=THIRD_PARTY_LICENSES.md
MODELS=MODEL_LICENSES.md

# Where an Apache-2.0 tag must never be, as extended regexes on the path.
NOT_OURS='^(third_party/|docs/legal/|vendor/|platforms/k230/patches/|docs/design/brand/|docs/design/rift/|ui/pocketui/fonts/|THIRD_PARTY_NOTICES\.txt$)'
# First-party source: what the header rule applies to.
FIRST_PARTY_SRC='^(apps|core|services|protocols|tools|ui|tests)/.*\.(c|h|cpp|hpp|sh|py|js|ps1)$|^platforms/k230/scripts/[^/]+\.sh$|^platforms/k230/rootfs_overlay/etc/init\.d/S[0-9]+[a-z0-9-]+$|^Makefile$|(^|/)CMakeLists\.txt$'

# ---- SPDX lines --------------------------------------------------------------
# path<TAB>value for every tag in a non-Markdown file (prose may quote the tag).
git grep -I -o -E "${TAG}:[[:space:]]*[^*]*" -- ':!*.md' 2>/dev/null |
    sed -e "s/:${TAG}:[[:space:]]*/	/" -e 's/[[:space:]]*\(\*\/\|-->\)\{0,1\}[[:space:]]*$//' > "$TMP/tags"
check "the tags could be read (the scan found this file's own)" \
    "$(grep -q -x -F "tests/license_audit_test.sh	Apache-2.0" "$TMP/tags" && echo 1 || echo 0)"
exempt() { grep -v -E '^[[:space:]]*(#|$)' "$EXEMPT" 2>/dev/null | awk '{print $1}' | sort -u; }

# SPDX licence-expression syntax, simple form: ids joined by AND, OR, WITH.
bad=$(awk -F '\t' '$2 !~ /^[A-Za-z0-9.+-]+( (AND|OR|WITH) [A-Za-z0-9.+-]+)*$/ {print $1": "$2}' "$TMP/tags")
check "every SPDX line is a well-formed licence expression${bad:+ (not: $bad)}" "$([ -z "$bad" ] && echo 1 || echo 0)"

# Apache-2.0 tags where the material is not the project's to license.
misplaced() { # <tags file>
    awk -F '\t' '$2 ~ /(^|[ (])Apache-2\.0($|[ )])/ {print $1}' "$1" | grep -E "$NOT_OURS" | sort -u
}
# Apache-2.0 tags on generated files: their licence follows their inputs.
generated() { # <tags file>
    awk -F '\t' '$2 ~ /Apache-2\.0/ {print $1}' "$1" | sort -u | while IFS= read -r f; do
        head -3 "$f" 2>/dev/null | grep -q -i -E 'generated by|do not edit' && printf '%s\n' "$f"
    done
}
hits=$(misplaced "$TMP/tags")
check "no Apache-2.0 SPDX line on third-party, legal, patch, supplied-design or font material${hits:+ (found: $hits)}" \
    "$([ -z "$hits" ] && echo 1 || echo 0)"
gen=$(generated "$TMP/tags")
check "and none on a generated file${gen:+ (found: $gen)}" "$([ -z "$gen" ] && echo 1 || echo 0)"
# Controls: the same two rules, on tags that break them.
printf '/* Generated by x. Do not edit. */\n' > "$TMP/gen.c"
printf 'platforms/k230/patches/linux/0099-x.patch\tApache-2.0\nthird_party/notices/texts/x.txt\tMIT OR Apache-2.0\n%s\tApache-2.0\n' \
    "$TMP/gen.c" > "$TMP/badtags"
check "the placement rule refuses a tag on a kernel patch and on a notices text (control)" \
    "$([ "$(misplaced "$TMP/badtags" | wc -l)" = 2 ] && echo 1 || echo 0)"
check "and the generated-file rule a tag on a generated file (control)" \
    "$([ "$(generated "$TMP/badtags")" = "$TMP/gen.c" ] && echo 1 || echo 0)"

grep -E "$FIRST_PARTY_SRC" "$TMP/files" | grep -v -E "$NOT_OURS" | sort -u > "$TMP/fp"
exempt > "$TMP/exempt"
# A first-party file that is partly someone else's says so with a compound
# expression (Apache-2.0 AND MIT) and is on the exemption list with the reason.
other=$(awk -F '\t' 'NR == FNR {fp[$1] = 1; next} ($1 in fp) && $2 != "Apache-2.0" {print $1}' "$TMP/fp" "$TMP/tags" |
        sort -u | comm -23 - "$TMP/exempt" | tr '\n' ' ')
check "first-party sources that carry a tag say Apache-2.0, unless listed as mixed${other:+ (other: $other)}" \
    "$([ -z "$other" ] && echo 1 || echo 0)"
mixed=$(awk -F '\t' 'NR == FNR {fp[$1] = 1; next} ($1 in fp) && $2 != "Apache-2.0" && $2 !~ /^Apache-2\.0 AND / {print $1": "$2}' \
        "$TMP/fp" "$TMP/tags")
check "and a mixed one still names Apache-2.0 for the project's part${mixed:+ (not: $mixed)}" \
    "$([ -z "$mixed" ] && echo 1 || echo 0)"

tbd=$(git grep -l -F 'License: see LICENSE (TBD)' -- . ':!docs/' ':!tests/license_audit_test.sh' 2>/dev/null)
check "no file still points to the undecided licence${tbd:+ (still: $(printf '%s' "$tbd" | tr '\n' ' '))}" \
    "$([ -z "$tbd" ] && echo 1 || echo 0)"

# ---- every first-party source file has its header ---------------------------
awk -F '\t' '$2 == "Apache-2.0" {print $1}' "$TMP/tags" | sort -u > "$TMP/apache"
missing=$(comm -23 "$TMP/fp" "$TMP/apache" | comm -23 - "$TMP/exempt" | tr '\n' ' ')
check "every first-party source file carries the Apache-2.0 SPDX line or is listed with a reason${missing:+ (missing: $missing)}" \
    "$([ -z "$missing" ] && echo 1 || echo 0)"
stale=""
for f in $(cat "$TMP/exempt"); do grep -qx -F "$f" "$TMP/files" || stale="$stale $f"; done
check "the exemption list names only tracked files${stale:+ (gone:$stale)}" "$([ -z "$stale" ] && echo 1 || echo 0)"
noreason=$(grep -v -E '^[[:space:]]*(#|$)' "$EXEMPT" 2>/dev/null | awk 'NF < 2 {print $1}')
check "and gives a reason for each${noreason:+ (no reason: $noreason)}" "$([ -z "$noreason" ] && echo 1 || echo 0)"

# ---- the root files -----------------------------------------------------------
check "LICENSE, NOTICE, THIRD_PARTY_LICENSES.md and MODEL_LICENSES.md are tracked" \
    "$(for f in LICENSE NOTICE "$TPL" "$MODELS"; do grep -qx -F "$f" "$TMP/files" || exit 1; done; echo 1)"
ids=$(grep -v -E '^[[:space:]]*(#|$)' "$SOURCES" | awk -F ' [|] ' '{print $1}' | sed 's/[[:space:]]*$//')
absent=""
for i in $ids; do grep -q -F "\`$i\`" "$TPL" || absent="$absent $i"; done
check "every component the notices ship has a row in THIRD_PARTY_LICENSES.md${absent:+ (absent:$absent)}" \
    "$([ -z "$absent" ] && echo 1 || echo 0)"
# The Canaan SDK licence (pos-vision's libmmz and adapted samples) is a copy
# kept here with its CRLF line ends made LF. Compared where the pinned SDK is
# checked out; its entry must name the SDK commit the build pins.
CANAAN=docs/legal/third-party/canaan-k230-linux-sdk-LICENSE.txt
SDKLIC=vendor/T-Display-K230/k230_linux_sdk/LICENSE
if [ -f "$SDKLIC" ]; then
    check "the Canaan licence copy is the pinned SDK's LICENSE, line ends aside" \
        "$(tr -d '\r' < "$SDKLIC" | cmp -s - "$CANAAN" && echo 1 || echo 0)"
fi
check "and its notices entry names the SDK commit the build pins" \
    "$(grep -q "^canaan-k230-sdk [|] .*SDK commit $(tr -d '\r\n' < platforms/k230/vendor_sdk_commit.txt) " "$SOURCES" && echo 1 || echo 0)"
# A file that adapts someone else's code names the licence text of what it
# adapted, and that text is one the notices or docs/legal keep.
bad=""
for f in $(awk -F '\t' '$2 ~ /^Apache-2\.0 AND / {print $1}' "$TMP/tags" | sort -u); do
    t=$(grep -o -E '(third_party/notices/texts|docs/legal/third-party)/[A-Za-z0-9_.-]+\.txt' "$f" | head -1)
    [ -n "$t" ] && [ -f "$t" ] || bad="$bad $f"
done
check "every file tagged Apache-2.0 AND <licence> points to a kept licence text${bad:+ (not:$bad)}" "$([ -z "$bad" ] && echo 1 || echo 0)"

# ---- the public-source candidate (B2, B1R, B3) ---------------------------------
# docs/licensing/public-source-exclude.txt keeps material in this private
# repository but out of the tree tools/legal/public_source_tree.sh exports.
PSX=docs/licensing/public-source-exclude.txt
psx_entries() { tr -d '\r' < "$PSX" | grep -v -E '^[[:space:]]*(#|$)' | sed -E 's/[[:space:]]+(B[0-9A-Z]+)[[:space:]].*$//'; }
gone=""
while IFS= read -r e; do [ -n "$(git ls-files -- "$e")" ] || gone="$gone [$e]"; done < <(psx_entries)
check "every public-source exclusion names tracked files${gone:+ (none:$gone)}" "$([ -z "$gone" ] && echo 1 || echo 0)"
# Nothing a build, a generator or a test reads may be excluded; a comment that
# names an excluded path is fine. tests/meshcored_lint.sh names
# docs/design/rift only inside the pattern of includes it refuses; it reads
# nothing there.
used=""
while IFS= read -r e; do
    hits=$(git grep -n -F "${e%/}" -- Makefile '*CMakeLists.txt' platforms/k230/scripts platforms/k230/package tools tests \
               ':!tests/license_audit_test.sh' ':!tests/meshcored_lint.sh' 2>/dev/null |
           grep -v -E '^[^:]+:[0-9]+:[[:space:]]*(#|\*|/\*|//)')
    [ -z "$hits" ] || used="$used [$e]"
done < <(psx_entries)
check "no build, generator or test input is excluded${used:+ (read:$used)}" "$([ -z "$used" ] && echo 1 || echo 0)"
# The exporter, executed: the design tool's runtime, design zips, bundled
# pages and supplied fonts are not in the candidate, and what the build needs
# is. (The RIFT .dc.html is the owner's design document and may be in it; it
# only renders with the runtime, which may not.)
bash tools/legal/public_source_tree.sh --list HEAD > "$TMP/candidate" 2>"$TMP/candidate.err"
check "the public-source exporter lists a candidate" "$([ -s "$TMP/candidate" ] && echo 1 || echo 0)"
leak=$(git ls-tree -r --name-only HEAD | grep -E '(^|/)support\.js$|\.zip$|Design System\.html$|\.otf$' |
       grep -x -F -f - "$TMP/candidate")
check "no design-tool runtime, design zip, bundled page or supplied font is in it${leak:+ (in: $leak)}" "$([ -z "$leak" ] && echo 1 || echo 0)"
check "and it keeps LICENSE, NOTICE, the notices, the build files and the defconfig fragment" \
    "$(for f in LICENSE NOTICE THIRD_PARTY_NOTICES.txt Makefile ui/shell/CMakeLists.txt platforms/k230/configs/k230_pocketos.fragment; do
           grep -qx -F "$f" "$TMP/candidate" || exit 1; done; echo 1)"
# B3: the vendor board defconfig is composed at apply time, never kept here.
check "the repository keeps no copy of a vendor defconfig (B3)" \
    "$([ -z "$(git ls-files 'platforms/k230/configs/*defconfig*')" ] && echo 1 || echo 0)"

# ---- the asset inventory (B1) --------------------------------------------------
# docs/licensing/asset-inventory.txt gives every artwork, image and design
# asset a class; the first rule that matches decides. Paths may hold spaces,
# so a rule's pattern is everything before its class word.
INV=docs/licensing/asset-inventory.txt
CLASSES="ORIGINAL OWNER-VECTOR OWNER-AI-RASTER OWNER-DESIGN BRAND DERIVED-ART DERIVED-BRAND CAPTURE OWNER-REF DESIGN-EXPORT THIRD-PARTY THIRD-PARTY-NOTICED"
tr -d '\r' < "$INV" | awk -v cl="$CLASSES" '
    BEGIN { n = split(cl, c, " "); for (i = 1; i <= n; i++) ok[c[i]] = 1 }
    /^[[:space:]]*(#|$)/ { next }
    { for (i = 2; i <= NF; i++) if ($i in ok) { p = $1; for (j = 2; j < i; j++) p = p " " $j; print p "\t" $i; next }
      print "BAD\t" $0 }' > "$TMP/rules"
badrule=$(grep -c '^BAD	' "$TMP/rules")
check "every asset-inventory rule names a known class" "$([ "$badrule" = 0 ] && echo 1 || echo 0)"
grep -i -E '\.(png|jpe?g|webp|gif|svg|bmp|xrgb|bin|zip|otf|ttf|woff2?|blend|html|stl)$' "$TMP/files" > "$TMP/assets"
: > "$TMP/classified"; : > "$TMP/used_rules"
while IFS= read -r f; do
    cls=""
    while IFS='	' read -r pat c; do
        # shellcheck disable=SC2053  # the pattern is a glob on purpose
        if [[ "$f" == $pat ]]; then cls=$c; printf '%s\n' "$pat" >> "$TMP/used_rules"; break; fi
    done < "$TMP/rules"
    printf '%s\t%s\n' "$f" "${cls:-NONE}" >> "$TMP/classified"
done < "$TMP/assets"
none=$(awk -F '\t' '$2 == "NONE" {print $1}' "$TMP/classified" | head -5 | tr '\n' ' ')
check "every tracked asset has a class in the inventory${none:+ (none: $none)}" "$([ -z "$none" ] && echo 1 || echo 0)"
# Rules for the generated C art match no asset extension; they are matched
# against all tracked files instead.
unused=""
while IFS='	' read -r pat c; do
    grep -qx -F "$pat" "$TMP/used_rules" && continue
    hit=0
    while IFS= read -r f; do [[ "$f" == $pat ]] && { hit=1; break; }; done < "$TMP/files"
    [ "$hit" = 1 ] || unused="$unused [$pat]"
done < "$TMP/rules"
check "every inventory rule still matches a tracked file${unused:+ (stale:$unused)}" "$([ -z "$unused" ] && echo 1 || echo 0)"
# The reserved brand (docs/licensing/BRAND.md): every BRAND or DERIVED-BRAND
# file, assets and the generated C mark alike, is listed there and carries no
# Apache-2.0 tag.
brand_files=$( { awk -F '\t' '$2 == "BRAND" || $2 == "DERIVED-BRAND" {print $1}' "$TMP/classified"
                 while IFS='	' read -r pat c; do
                     [ "$c" = BRAND ] || [ "$c" = DERIVED-BRAND ] || continue
                     while IFS= read -r f; do [[ "$f" == $pat ]] && printf '%s\n' "$f"; done < "$TMP/files"
                 done < "$TMP/rules"; } | sort -u)
unlisted=""
for f in $brand_files; do
    d=$(dirname "$f")/
    grep -q -F "\`$f\`" docs/licensing/BRAND.md || grep -q -F "\`$d\`" docs/licensing/BRAND.md || unlisted="$unlisted $f"
done
check "every reserved brand file is listed in docs/licensing/BRAND.md${unlisted:+ (not:$unlisted)}" \
    "$([ -n "$brand_files" ] && [ -z "$unlisted" ] && echo 1 || echo 0)"
tagged=$(for f in $brand_files; do awk -F '\t' -v f="$f" '$1 == f && $2 ~ /Apache-2\.0/ {print f}' "$TMP/tags"; done)
check "and none carries an Apache-2.0 SPDX tag${tagged:+ (tagged: $tagged)}" "$([ -z "$tagged" ] && echo 1 || echo 0)"
check "NOTICE says the brand files are not under Apache-2.0 and points to their terms" \
    "$(grep -q 'docs/licensing/BRAND.md' NOTICE && grep -q -i 'not licensed under' NOTICE && echo 1 || echo 0)"
# What is classed as reference, design export or third-party is out of the
# public-source candidate.
leaked=$(awk -F '\t' '$2 == "OWNER-REF" || $2 == "DESIGN-EXPORT" || $2 == "THIRD-PARTY" {print $1}' "$TMP/classified" |
         grep -x -F -f - "$TMP/candidate" | head -5 | tr '\n' ' ')
check "reference, design-export and third-party assets are all out of the candidate${leaked:+ (in: $leaked)}" \
    "$([ -z "$leaked" ] && echo 1 || echo 0)"
grep -x -F -f "$TMP/candidate" "$TMP/assets" > "$TMP/cand_assets" || true
for c in $CLASSES; do
    k=$(awk -F '\t' -v c="$c" 'NR == FNR {in_c[$1] = 1; next} ($1 in in_c) && $2 == c' "$TMP/cand_assets" "$TMP/classified" | wc -l)
    [ "$k" -gt 0 ] && echo "     candidate assets $c: $k"
done

# ---- models ------------------------------------------------------------------
committed=$(grep -i -E '\.(kmodel|onnx|tflite|pt|pth|safetensors|gguf|caffemodel|weights)$' "$TMP/files")
check "no model file is committed${committed:+ (found: $committed)}" "$([ -z "$committed" ] && echo 1 || echo 0)"

# The rows of MODEL_LICENSES.md's matrix that name a Doors model path.
model_row() { grep -F "\`/usr/share/doors/vision/$1\`" "$2" | head -1; }
# Model files a package file installs into the image: names under
# usr/share/doors/vision/ on its install lines (a line that removes one is
# not an install).
installed_models() { # <package .mk> <Makefile>
    cat "$@" | grep -E '\$\((INSTALL|TARGET_DIR)\)|^\s+install ' | grep -v -E '^\s*rm( |$)' |
        grep -o -E 'usr/share/doors/vision/[A-Za-z0-9_.-]+' | sed 's#.*/##' | sort -u
}
# UNKNOWN-status models allowed into an image, as <file>:<notices id>. None
# since 0.3.5: the internal-only yolov8n.kmodel (docs/LICENSING.md item 10)
# no longer ships.
INTERNAL_OK=""
model_rules() { # <package .mk> <Makefile> <MODEL_LICENSES.md> <SOURCES>; prints each violation
    local m row allowed note
    for m in $(installed_models "$1" "$2"); do
        row=$(model_row "$m" "$3")
        [ -n "$row" ] || { echo "$m installed but not in MODEL_LICENSES.md"; continue; }
        case "$row" in *"EXTERNAL ONLY"*) case "$row" in *UNKNOWN*"internal images only"*|*"internal images only"*UNKNOWN*) ;; *)
            echo "$m is EXTERNAL ONLY but installed"; continue ;; esac ;; esac
        case "$row" in
            *"OWNER-LICENSED - THIRD-PARTY QUESTIONS OPEN"*)
                printf '%s\n' "$row" | grep -q 'THIRD_PARTY_NOTICES.txt `' || echo "$m: its row names no notices entry"
                for n in $(printf '%s\n' "$row" | grep -o -E 'THIRD_PARTY_NOTICES.txt( `[a-z0-9-]+`( and)?)+' |
                           grep -o -E '`[a-z0-9-]+`' | tr -d '`'); do
                    grep -q "^${n} *|" "$4" || echo "$m: no notices entry ${n}"
                done ;;
            *REDISTRIBUTABLE*) ;;
            *UNKNOWN*)
                allowed=""
                for a in $INTERNAL_OK; do [ "${a%%:*}" = "$m" ] && allowed="${a#*:}"; done
                if [ -z "$allowed" ]; then echo "$m has status UNKNOWN and is installed"
                else
                    printf '%s\n' "$row" | grep -q 'internal images only' || echo "$m: its row does not say internal images only"
                    grep -q "^${allowed} *|" "$4" || echo "$m: no notices entry ${allowed}"
                fi ;;
            *) echo "$m: its row has no status an image may carry" ;;
        esac
    done
}
v=$(model_rules "$MK" Makefile "$MODELS" "$SOURCES")
check "every installed model is listed, and none of unknown terms is installed${v:+ ($v)}" \
    "$([ -z "$v" ] && echo 1 || echo 0)"
inst=$(installed_models "$MK" Makefile | tr '\n' ' ')
check "the package installs one model, R0 (0.3.6)${inst:+ (installs: $inst)}" \
    "$([ "$inst" = 'det-r0-traffic6-yolox-tiny-416.kmodel ' ] && echo 1 || echo 0)"
check "R0's row is OWNER-LICENSED (Apache-2.0) with its third-party questions open, not REDISTRIBUTABLE" \
    "$(model_row det-r0-traffic6-yolox-tiny-416.kmodel "$MODELS" | grep -q "OWNER-LICENSED - THIRD-PARTY QUESTIONS OPEN" && model_row det-r0-traffic6-yolox-tiny-416.kmodel "$MODELS" | grep -q 'The weights: Apache-2.0' && echo 1 || echo 0)"
R0SUM=tools/vision/r0-model.sha256
check "R0 is pinned by its sha256, on one line, under the name it is installed as" \
    "$([ "$(cat "$R0SUM")" = '94a20ac01692d9a7b6dfc7f1497c1024141fcef997ff055c219a03e105ded268  det-r0-traffic6-yolox-tiny-416.kmodel' ] && echo 1 || echo 0)"
check "the install checks R0 against that pin before installing it" \
    "$(sed -n '/^define POCKETOS_INSTALL_TARGET_CMDS/,/^endef/p' "$MK" | grep -q -F 'sha256sum -c --strict --quiet $(@D)/tools/vision/r0-model.sha256) &&' && echo 1 || echo 0)"
check "and removes an earlier build's copy first" \
    "$(sed -n '/^define POCKETOS_INSTALL_TARGET_CMDS/,/^endef/p' "$MK" | grep -q -F 'rm -f $(TARGET_DIR)/usr/share/doors/vision/det-r0-traffic6-yolox-tiny-416.kmodel' && echo 1 || echo 0)"
check "apply_to_sdk.sh stages R0 only with the pinned hash" \
    "$(grep -q -F 'tools/vision/r0-model.sha256' platforms/k230/scripts/apply_to_sdk.sh &&
       grep -q -F '"${R0_GOT}" != "${R0_SHA}"' platforms/k230/scripts/apply_to_sdk.sh && echo 1 || echo 0)"
ext=$(grep -F 'EXTERNAL ONLY' "$MODELS" | grep -o -E '`/usr/share/doors/vision/[A-Za-z0-9_.-]+`' | tr -d '`' | sed 's#.*/##' | sort -u)
check "MODEL_LICENSES.md names the EXTERNAL ONLY models (upstream YOLOX, face_det, text_det, text_rec, text_dict, face_embed)" \
    "$([ "$(printf '%s\n' $ext | tr '\n' ' ')" = 'det-upstream-yolox-tiny-416.kmodel face_det.kmodel face_embed.kmodel text_det.kmodel text_dict.txt text_rec.kmodel ' ] && echo 1 || echo 0)"
# Executed against packages that break the rules.
cp "$MK" "$TMP/ext.mk"
printf '\t$(INSTALL) -D -m 0644 x/face_det.kmodel $(TARGET_DIR)/usr/share/doors/vision/face_det.kmodel\n' >> "$TMP/ext.mk"
check "a package that installs an EXTERNAL ONLY model is refused (control)" \
    "$(model_rules "$TMP/ext.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'face_det.kmodel' && echo 1 || echo 0)"
cp "$MK" "$TMP/new.mk"
printf '\t$(INSTALL) -D -m 0644 x/mystery.kmodel $(TARGET_DIR)/usr/share/doors/vision/mystery.kmodel\n' >> "$TMP/new.mk"
check "and so is one that installs a model MODEL_LICENSES.md does not list (control)" \
    "$(model_rules "$TMP/new.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'mystery.kmodel installed but not in' && echo 1 || echo 0)"
cp "$MK" "$TMP/yolo.mk"
printf '\t$(INSTALL) -D -m 0644 x/yolov8n.kmodel $(TARGET_DIR)/usr/share/doors/vision/yolov8n.kmodel\n' >> "$TMP/yolo.mk"
check "and so is one that installs the AGPL-labelled yolov8n.kmodel again (control)" \
    "$(model_rules "$TMP/yolo.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'yolov8n.kmodel has status UNKNOWN' && echo 1 || echo 0)"
cp "$MK" "$TMP/up.mk"
printf '\t$(INSTALL) -D -m 0644 x/det-upstream-yolox-tiny-416.kmodel $(TARGET_DIR)/usr/share/doors/vision/det-upstream-yolox-tiny-416.kmodel\n' >> "$TMP/up.mk"
check "and so is one that installs the bench A/B's upstream YOLOX-Tiny (control)" \
    "$(model_rules "$TMP/up.mk" Makefile "$MODELS" "$SOURCES" | grep -q 'det-upstream-yolox-tiny-416.kmodel is EXTERNAL ONLY' && echo 1 || echo 0)"
grep -v '^r0-training-data ' "$SOURCES" > "$TMP/sources-no-r0"
check "and R0 without its training-data notice (control)" \
    "$(model_rules "$MK" Makefile "$MODELS" "$TMP/sources-no-r0" | grep -q 'no notices entry r0-training-data' && echo 1 || echo 0)"
sed 's/OWNER-LICENSED - THIRD-PARTY QUESTIONS OPEN/PENDING/' "$MODELS" > "$TMP/models-nostatus"
check "and R0 whose row loses its status (control)" \
    "$(model_rules "$MK" Makefile "$TMP/models-nostatus" "$SOURCES" | grep -q 'det-r0-traffic6-yolox-tiny-416.kmodel: its row has no status' && echo 1 || echo 0)"

# The target-wide refusal (pocketos.mk, POCKETOS_REFUSE_DETECTOR_MODELS): a
# vendor package, a stale build tree or a rename must not bring an
# Ultralytics YOLO kmodel back. The hook is registered, its list holds the
# SDK's four, and its body is executed against fake target trees.
REFUSED=tools/vision/refused-models.sha256
check "the package refuses the vendor yolo demo package" \
    "$(grep -q '^ifeq ($(BR2_PACKAGE_YOLO),y)' "$MK" && grep -q 'BR2_PACKAGE_YOLO installs' "$MK" && echo 1 || echo 0)"
check "the install removes a copy an earlier build left in the target" \
    "$(sed -n '/^define POCKETOS_INSTALL_TARGET_CMDS/,/^endef/p' "$MK" | grep -q 'rm -f $(TARGET_DIR)/usr/share/doors/vision/yolov8n.kmodel' && echo 1 || echo 0)"
check "the refusal runs after every package (target-finalize hook)" \
    "$(grep -q '^POCKETOS_TARGET_FINALIZE_HOOKS += POCKETOS_REFUSE_DETECTOR_MODELS' "$MK" && echo 1 || echo 0)"
check "its list names the SDK's yolov8n, yolov5n, yolo11n and yolo26n by hash" \
    "$([ "$(grep -c -E '^[0-9a-f]{64}  yolo[a-z0-9]*\.kmodel$' "$REFUSED")" = 4 ] &&
       grep -q '^0b4bcdd3eef7ad05d827127ec630d2354659f6db1b0c627ecb4af32cb2004a09 ' "$REFUSED" && echo 1 || echo 0)"
check "and the bench A/B's upstream YOLOX-Tiny, and never R0" \
    "$(grep -q '^8c304651b4c9115f112680f1abb8c604592902f92147368a716a0fb9390ee354  det-upstream-yolox-tiny-416.kmodel$' "$REFUSED" &&
       ! grep -q "^$(cut -c1-64 tools/vision/r0-model.sha256) " "$REFUSED" && echo 1 || echo 0)"
VYOLO=vendor/T-Display-K230/k230_linux_sdk/buildroot-overlay/package/yolo/utils
if [ -d "$VYOLO" ]; then
    miss=""
    for f in "$VYOLO"/*.kmodel; do grep -q "^$(sha256sum < "$f" | cut -c1-64) " "$REFUSED" || miss="$miss $(basename "$f")"; done
    check "every kmodel of the vendor yolo package is on the list${miss:+ (missing:$miss)}" "$([ -z "$miss" ] && echo 1 || echo 0)"
fi
# The hook's shell, as make would run it: $$ is $, the two variables set.
refuse() { # <target dir> <refused list>
    sed -n '/^define POCKETOS_REFUSE_DETECTOR_MODELS/,/^endef/p' "$MK" | sed '1d;$d' |
        sed -e 's/\$\$/$/g' -e "s#\$(TARGET_DIR)#$1#g" -e "s#\$(POCKETOS_DIR)/tools/vision/refused-models.sha256#$2#g" > "$TMP/refuse.sh"
    bash "$TMP/refuse.sh" > /dev/null 2>&1
}
mkdir -p "$TMP/t1/root/app/face_detect" "$TMP/t2/usr/share/demo" "$TMP/t3/usr/share/x"
printf 'face' > "$TMP/t1/root/app/face_detect/face_detection_320.kmodel"
check "a target with only other models passes (control)" "$(refuse "$TMP/t1" "$REFUSED" && echo 1 || echo 0)"
printf 'x' > "$TMP/t2/usr/share/demo/YOLO11N.kmodel"
check "a YOLO kmodel by name is refused (control)" "$(refuse "$TMP/t2" "$REFUSED" && echo 0 || echo 1)"
printf 'renamed' > "$TMP/t3/usr/share/x/detector.kmodel"
printf '%s  renamed.kmodel\n' "$(sha256sum < "$TMP/t3/usr/share/x/detector.kmodel" | cut -c1-64)" > "$TMP/refused"
check "and a listed one under another name, by its hash (control)" "$(refuse "$TMP/t3" "$TMP/refused" && echo 0 || echo 1)"

echo "license_audit_test: $failed failure(s)"
exit $((failed > 0))
