/* Generated by tools/design/gen_doors_ui.py. Do not edit; regenerate. */
#ifndef POS_GLYPHS_H
#define POS_GLYPHS_H

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

/* DOORS B system glyphs, A8 32 x 32 (pos_glyphs.c). */
extern const lv_image_dsc_t pos_glyph_lock;
extern const lv_image_dsc_t pos_glyph_power;
extern const lv_image_dsc_t pos_glyph_wifi;
extern const lv_image_dsc_t pos_glyph_radio;
extern const lv_image_dsc_t pos_glyph_sun;
extern const lv_image_dsc_t pos_glyph_display;
extern const lv_image_dsc_t pos_glyph_info;
extern const lv_image_dsc_t pos_glyph_settings;
extern const lv_image_dsc_t pos_glyph_apps;
extern const lv_image_dsc_t pos_glyph_network;
extern const lv_image_dsc_t pos_glyph_mesh;
extern const lv_image_dsc_t pos_glyph_sound;
extern const lv_image_dsc_t pos_glyph_mode;

#endif
