#!/usr/bin/env python3
# Copyright (c) 2026 PocketOS authors.
# SPDX-License-Identifier: Apache-2.0
"""Generate ui/pocketui/pos_brand_mark.c, the Doors compact mark as an A8 mask.

    gen_brand_mark.py [doors-mark.png] [pos_brand_mark.c]

Defaults: docs/design/brand/doors-threshold/brand/doors-mark.png into
ui/pocketui/pos_brand_mark.c. The generated file is committed, like the
fonts, so a build needs neither this script nor the PNG;
tests/brand_mark_test.sh fails if it no longer matches its source.

The source is the package's tintable mark: white on transparent. Only its
alpha channel is kept, so the mark has no colour of its own and is drawn in
the image_recolor of its style (POS_STYLE_BRAND_MARK, accent_primary), which
the theme engine rewrites on every theme and mode change (DS §8, §19). A
source with any other colour under a visible pixel is refused: that colour
would be thrown away without anyone deciding to.

The canvas is trimmed to the smallest box holding every visible pixel; only
fully transparent pixels fall outside it, so nothing of the mark is lost, and
nothing is scaled. Standard library only.
"""
import hashlib
import os
import sys
from pathlib import Path

sys.dont_write_bytecode = True          # a build must leave no __pycache__ in the tree
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngstrict import PngError, read_png  # noqa: E402

SYMBOL = "pos_brand_mark"


def mask(png, src):
    if png.colour_type != 6:
        raise PngError("%s: no alpha channel; the mark must be white on transparent" % src)
    w = png.width
    alpha = png.rgba[3::4]
    visible = [i for i, a in enumerate(alpha) if a]
    if not visible:
        raise PngError("%s: every pixel is transparent" % src)
    for i in visible:
        if png.rgba[i * 4:i * 4 + 3] != b"\xff\xff\xff":
            raise PngError("%s: pixel (%d, %d) is #%s, not white; a tint mask carries no colour"
                           % (src, i % w, i // w, png.rgba[i * 4:i * 4 + 3].hex()))
    x0 = min(i % w for i in visible)
    x1 = max(i % w for i in visible)
    y0 = min(i // w for i in visible)
    y1 = max(i // w for i in visible)
    rows = [bytes(alpha[y * w + x0:y * w + x1 + 1]) for y in range(y0, y1 + 1)]
    return x0, y0, x1 - x0 + 1, y1 - y0 + 1, rows


def main():
    root = Path(__file__).resolve().parents[2]
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "docs/design/brand/doors-threshold/brand/doors-mark.png"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "ui/pocketui/pos_brand_mark.c"
    try:
        png = read_png(str(src))
        x0, y0, w, h, rows = mask(png, src)
    except (PngError, OSError) as e:
        print("gen_brand_mark: %s" % e, file=sys.stderr)
        return 1
    try:
        shown = src.resolve().relative_to(root).as_posix()
    except ValueError:
        shown = src.name
    digest = hashlib.sha256(src.read_bytes()).hexdigest()
    lines = [
        "/* Generated by tools/design/gen_brand_mark.py from",
        " * %s" % shown,
        " * (sha256 %s)." % digest,
        " * Do not edit; regenerate.",
        " *",
        " * The Doors compact mark as an LVGL A8 alpha mask, %d x %d: the source's" % (w, h),
        " * %d x %d canvas trimmed at (%d, %d) to the visible pixels, alpha kept" % (png.width, png.height, x0, y0),
        " * exactly. It has no colour; its style's image_recolor draws it (DS §19). */",
        "#ifdef LV_LVGL_H_INCLUDE_SIMPLE",
        '#include "lvgl.h"',
        "#else",
        '#include "lvgl/lvgl.h"',
        "#endif",
        "",
        "static const uint8_t %s_map[] LV_ATTRIBUTE_MEM_ALIGN = {" % SYMBOL,
    ]
    for r in rows:
        lines.append("    " + ",".join("0x%02x" % v for v in r) + ",")
    lines += [
        "};",
        "",
        "const lv_image_dsc_t %s = {" % SYMBOL,
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
        "    .header.cf = LV_COLOR_FORMAT_A8,",
        "    .header.flags = 0,",
        "    .header.w = %d," % w,
        "    .header.h = %d," % h,
        "    .header.stride = %d," % w,
        "    .data_size = sizeof(%s_map)," % SYMBOL,
        "    .data = %s_map," % SYMBOL,
        "};",
        "",
    ]
    dst.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("gen_brand_mark: %s -> %s, %d x %d A8" % (shown, dst, w, h))
    return 0


if __name__ == "__main__":
    sys.exit(main())
