#!/usr/bin/env python3
"""Generate ui/pocketui/pos_app_icons.c, the Doors app icons as A8 masks.

    gen_app_icons.py [ICON_DIR] [pos_app_icons.c]

Defaults: docs/design/brand/doors-threshold/icons/png-32 into
ui/pocketui/pos_app_icons.c. The generated file is committed, like the fonts
and the brand mark, so a build needs neither this script nor the PNGs;
tests/app_icons_test.sh fails if it no longer matches its sources.

Every PNG in ICON_DIR becomes one `const lv_image_dsc_t pos_app_icon_<name>`,
where <name> is the file name, which is the app's id. The sources are the
package's tintable icons: white on transparent. Only the alpha channel is
kept, antialiasing included, so an icon has no colour of its own and is drawn
in the image_recolor of its style (POS_STYLE_APP_ICON, accent_primary), which
the theme engine rewrites on every theme and mode change (DS §8). A source
with any other colour under a visible pixel is refused: that colour would be
thrown away without anyone deciding to.

The whole canvas is kept, not trimmed: the package places each icon inside
the same square cell, and trimming would move every icon by a different
amount. Nothing is scaled. All icons must have the same size. Standard
library only.
"""
import hashlib
import os
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True          # a build must leave no __pycache__ in the tree
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngstrict import PngError, read_png  # noqa: E402

PREFIX = "pos_app_icon_"


def mask(png, src):
    if png.colour_type != 6:
        raise PngError("%s: no alpha channel; an icon must be white on transparent" % src)
    w = png.width
    alpha = png.rgba[3::4]
    visible = [i for i, a in enumerate(alpha) if a]
    if not visible:
        raise PngError("%s: every pixel is transparent" % src)
    for i in visible:
        if png.rgba[i * 4:i * 4 + 3] != b"\xff\xff\xff":
            raise PngError("%s: pixel (%d, %d) is #%s, not white; a tint mask carries no colour"
                           % (src, i % w, i // w, png.rgba[i * 4:i * 4 + 3].hex()))
    return [bytes(alpha[y * w:(y + 1) * w]) for y in range(png.height)]


def main():
    root = Path(__file__).resolve().parents[2]
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "docs/design/brand/doors-threshold/icons/png-32"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "ui/pocketui/pos_app_icons.c"
    try:
        shown_dir = src_dir.resolve().relative_to(root).as_posix()
    except ValueError:
        shown_dir = src_dir.name
    icons = []
    try:
        files = sorted(p for p in src_dir.iterdir() if p.suffix == ".png")
        if not files:
            raise PngError("%s: no PNG files" % src_dir)
        for p in files:
            if not re.fullmatch(r"[a-z][a-z0-9_]*", p.stem):
                raise PngError("%s: the file name is not an app id usable in a C name" % p)
            png = read_png(str(p))
            rows = mask(png, p)
            want = (icons[0][2], icons[0][3]) if icons else (png.width, png.width)
            if (png.width, png.height) != want:
                raise PngError("%s: %d x %d; every icon must be the same square size"
                               % (p, png.width, png.height))
            icons.append((p.stem, rows, png.width, png.height,
                          hashlib.sha256(p.read_bytes()).hexdigest()))
    except (PngError, OSError) as e:
        print("gen_app_icons: %s" % e, file=sys.stderr)
        return 1
    w, h = icons[0][2], icons[0][3]
    lines = [
        "/* Generated by tools/design/gen_app_icons.py from",
        " * %s/<id>.png. Do not edit; regenerate." % shown_dir,
        " *",
        " * The Doors app icons as LVGL A8 alpha masks, %d x %d each, the whole" % (w, h),
        " * canvas, alpha kept exactly. They have no colour; the style's",
        " * image_recolor draws them (POS_STYLE_APP_ICON).",
        " *",
    ]
    lines += [" *   %-10s sha256 %s" % (name, digest) for name, _, _, _, digest in icons]
    lines += [
        " */",
        "#ifdef LV_LVGL_H_INCLUDE_SIMPLE",
        '#include "lvgl.h"',
        "#else",
        '#include "lvgl/lvgl.h"',
        "#endif",
    ]
    for name, rows, _, _, _ in icons:
        sym = PREFIX + name
        lines += ["", "static const uint8_t %s_map[] LV_ATTRIBUTE_MEM_ALIGN = {" % sym]
        for r in rows:
            lines.append("    " + ",".join("0x%02x" % v for v in r) + ",")
        lines += [
            "};",
            "",
            "const lv_image_dsc_t %s = {" % sym,
            "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
            "    .header.cf = LV_COLOR_FORMAT_A8,",
            "    .header.flags = 0,",
            "    .header.w = %d," % w,
            "    .header.h = %d," % h,
            "    .header.stride = %d," % w,
            "    .data_size = sizeof(%s_map)," % sym,
            "    .data = %s_map," % sym,
            "};",
        ]
    lines.append("")
    dst.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("gen_app_icons: %s -> %s, %d icons, %d x %d A8: %s"
          % (shown_dir, dst, len(icons), w, h, " ".join(i[0] for i in icons)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
