#!/usr/bin/env python3
# Copyright (c) 2026 PocketOS authors.
# SPDX-License-Identifier: Apache-2.0
"""Generate ui/pocketui/pos_theme_table.h from docs/design/themes.json.

Only the Normal-mode base tokens are emitted; derived tokens and the Outdoor
and Night transforms are computed by pos_theme.c (POCKETOS-DS-v0.1 §4, §6).
tests/theme_test.c checks the engine against every value in the JSON.

Usage: gen_theme_table.py [themes.json] [pos_theme_table.h]
"""
import json
import sys
from pathlib import Path

BASE = [
    "bg", "surface", "surface_raised", "line", "text_primary", "text_secondary",
    "accent_primary", "accent_secondary", "status_ok", "status_warn",
    "status_error", "radio_rx", "radio_tx",
]

def main():
    root = Path(__file__).resolve().parents[2]
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "docs/design/themes.json"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "ui/pocketui/pos_theme_table.h"
    data = json.loads(src.read_text(encoding="utf-8"))
    order = data["theme_order"]
    fallback = data["fallback_theme"]
    lines = [
        "/* Generated by tools/design/gen_theme_table.py from docs/design/themes.json.",
        f" * Design System {data['version']} ({data['status']}, {data['generated']}).",
        " * Do not edit; regenerate. Normal-mode base tokens only (DS §5). */",
        "#ifndef POS_THEME_TABLE_H",
        "#define POS_THEME_TABLE_H",
        "",
        f'#define POS_THEME_FALLBACK_ID "{fallback}"',
        f"#define POS_THEME_TABLE_COUNT {len(order)}",
        "",
        "static const struct pos_theme_def pos_theme_table[POS_THEME_TABLE_COUNT] = {",
    ]
    for tid in order:
        theme = data["themes"][tid]
        normal = theme["modes"]["normal"]
        vals = ", ".join("0x" + normal[k].lstrip("#").lower() for k in BASE)
        lines.append(f'    {{ "{tid}", "{theme["name"]}", {{ {vals} }} }},')
    lines += ["};", "", "#endif", ""]
    dst.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {dst} ({len(order)} themes, fallback {fallback})")

if __name__ == "__main__":
    main()
